interface Pytanie {
    pytanie: string;
    kategoria: string;
    odpowiedź: string;
}

export const etapI: Pytanie[] = [
  { pytanie: "Jak nazywają się ziemniaki pokrojone w paski i smażone na oleju?", kategoria: "Kulinaria", odpowiedź: "Frytki" },
  { pytanie: "Gdzie piszemy licznik ułamka?", kategoria: "Matematyka", odpowiedź: "Na górze" },
  { pytanie: "Co uprawiała Steffi Graf?", kategoria: "Sport", odpowiedź: "Tenis ziemny" },
  { pytanie: "W którym roku wybuchła I wojna światowa?", kategoria: "Historia", odpowiedź: "1914" },
  { pytanie: "Które góry dominują w Chile?", kategoria: "Geografia", odpowiedź: "Andy" },
  { pytanie: "Którego dnia kwietnia wypada prima aprillis?", kategoria: "Obyczaje", odpowiedź: "1 kwietnia" },
  { pytanie: "Ile pestek mieści się w owocu palmy daktylowej?", kategoria: "Przyroda", odpowiedź: "Jedna" },
  { pytanie: "Ile pełnych tygodni ma rok kalendarzowy?", kategoria: "Inne", odpowiedź: "52" },
  { pytanie: "W którym państwie wynaleziono proch strzelniczy?", kategoria: "Historia", odpowiedź: "W Chinach" },
  { pytanie: "Jak nazywa się rodzaj muzyki ludowej z Jamajki upowszechnionej przez Boba Marleya?", kategoria: "Muzyka", odpowiedź: "Reggae" },
  { pytanie: "Które drzewo przedstawia korzenie rodzinne człowieka?", kategoria: "Inne", odpowiedź: "Genealogiczne" },
  { pytanie: "Którą roślinę określa nazwa sunflower?", kategoria: "Język angielski", odpowiedź: "Słonecznik" },
  { pytanie: "Jak nazywa się pomnik odkryty w 1886 roku przedstawiający posąg kobiety trzymającej płonącą pochodnię?", kategoria: "Geografia/Historia", odpowiedź: "Statua Wolności" },
  { pytanie: "Nad którą rzeką leży Płock?", kategoria: "Geografia Polski", odpowiedź: "Wisłą" },
  { pytanie: "Jak nazywa się bohaterka gier komputerowych z serii Tomb Raider?", kategoria: "Gry komputerowe", odpowiedź: "Lara Croft" },
  { pytanie: "Jak nazywa się największy żyjący współcześnie przedstawiciel rodziny kotów?", kategoria: "Przyroda", odpowiedź: "Tygrys" },
  { pytanie: "Jaką broń należy zakopać, aby puścić w niepamięć dawne urazy?", kategoria: "Przysłowia", odpowiedź: "Topór" },
  { pytanie: "Młodzieniec usługujący rycerzowi, przygotowujący się do stanu rycerskiego, to?", kategoria: "Historia", odpowiedź: "Giermek" },
  { pytanie: "Jak nazywa się pałeczka dyrygenta?", kategoria: "Muzyka", odpowiedź: "Batuta" },
  { pytanie: "Na które pytania odpowiada biernik?", kategoria: "Gramatyka", odpowiedź: "Kogo? Co?" },
  { pytanie: "Który ocean oddziela Europę od Ameryki?", kategoria: "Geografia", odpowiedź: "Atlantycki" },
  { pytanie: "W co zmienia się bohater książki Franza Kafki 'Przemiana'?", kategoria: "Literatura", odpowiedź: "W robaka" },
  { pytanie: "W którym państwie leży Czarnobyl?", kategoria: "Geografia", odpowiedź: "Na Ukrainie" },
  { pytanie: "Która piosenkarka wylansowała przeboje 'Like a virgin' i 'Material Girl'?", kategoria: "Muzyka", odpowiedź: "Madonna" },
  { pytanie: "Jak nazywa się ustawa zasadnicza ustalająca podstawy ustroju państwa?", kategoria: "Prawo", odpowiedź: "Konstytucja" },
  { pytanie: "Jak nazywa się autobus elektryczny zasilany z sieci zawieszonej nad drogą?", kategoria: "Technika", odpowiedź: "Trolejbus" },
  { pytanie: "Którego księcia wg kroniki Galla Anonima zjadły myszy?", kategoria: "Historia Polski", odpowiedź: "Popiela" },
  { pytanie: "Jakim skrótem literowym oznacza się osobę o nieustalonej tożsamości?", kategoria: "Prawo", odpowiedź: "NN" },
  { pytanie: "Tuńczyk jest rybą morską czy słodkowodną?", kategoria: "Przyroda", odpowiedź: "Morską" },
  { pytanie: "Przez jakie 'h' piszemy słowo charyzma?", kategoria: "Ortografia", odpowiedź: "Przez 'ch'" },
  { pytanie: "Jak nazywa się agent brytyjskiego wywiadu, bohater powieści Iana Fleminga?", kategoria: "Literatura/Film", odpowiedź: "James Bond" },
  { pytanie: "Czy Indianie to rdzenna ludność Indii?", kategoria: "Geografia", odpowiedź: "Nie" },
  { pytanie: "Jak nazywa się pierwszy Polak, który wygrał Turniej Czterech Skoczni?", kategoria: "Sport", odpowiedź: "Adam Małysz" },
  { pytanie: "Jak po polsku określany jest gatunek literatury po angielsku nazywany science-fiction?", kategoria: "Literatura", odpowiedź: "Fantastyka naukowa"},
  { pytanie: "Komu wg przysłowia zawadza rąbek u spódnicy?", kategoria: "Przysłowia", odpowiedź: "Złej baletnicy" },
  { pytanie: "Jak nazywały się podziemne cmentarze w starożytnym Rzymie?", kategoria: "Historia", odpowiedź: "Katakumby" },
  { pytanie: "O kimś, kto pisze brzydko i niewyraźnie, mówimy, że bazgrze jak?", kategoria: "Związki frazeologiczne", odpowiedź: "Świnia" },
  { pytanie: "Jak nazywa się czynność polegająca na łączeniu wapna palonego z wodą?", kategoria: "Chemia/Budownictwo", odpowiedź: "Gaszenie" },
  { pytanie: "Gdzie wg przysłowia nie należy wkładać palców?", kategoria: "Przysłowia", odpowiedź: "Między drzwi" },
  { pytanie: "Proszę rozwinąć skrót CBŚ.", kategoria: "Prawo/Polska", odpowiedź: "Centralne Biuro Śledcze" },
  { pytanie: "Czy laptop to to samo co notebook?", kategoria: "Informatyka", odpowiedź: "Tak" },
  { pytanie: "W którym państwie leży miasto Kalkuta?", kategoria: "Geografia", odpowiedź: "W Indiach" },
  { pytanie: "Ile belek ma na mundurze szeregowy?", kategoria: "Militaria", odpowiedź: "0" },
  { pytanie: "Jak nazywamy fragment tekstu zaczynający się od nowego wiersza?", kategoria: "Gramatyka/Literatura", odpowiedź: "Akapit" },
  { pytanie: "Czy kajakarstwo jest dyscypliną olimpijską?", kategoria: "Sport", odpowiedź: "Tak" },
  { pytanie: "Flaga którego państwa przedstawia czerwoną tarczę na białym tle?", kategoria: "Geografia/Flagi", odpowiedź: "Japonii" },
  { pytanie: "Kto jest autorem wiersza dla dzieci pt. 'Samochwała'?", kategoria: "Literatura", odpowiedź: "Jan Brzechwa" },
  { pytanie: "Proszę dokończyć przysłowie: 'Kazał pan...'?", kategoria: "Przysłowia", odpowiedź: '...musiał sam' },
  { pytanie: "Jaką postać przybrał Szatan, by kusić Ewę w Raju?", kategoria: "Religia", odpowiedź: "Postać węża" },
  { pytanie: "Czy papież jest głową Kościoła anglikańskiego?", kategoria: "Religia", odpowiedź: "Nie" },
  { pytanie: "Mural to malowidło ścienne czy ceglana ściana?", kategoria: "Sztuka", odpowiedź: "Malowidło ścienne" },
  { pytanie: "Jak po polsku nazywa się urządzenie zwane wariografem?", kategoria: "Technika/Prawo", odpowiedź: "Wykrywacz kłamstw" },
  { pytanie: "Co zgodnie z powiedzeniem jest dobre na frasunek?", kategoria: "Przysłowia", odpowiedź: "Trunek" },
  { pytanie: "Proszę rozwinąć skrót NFZ.", kategoria: "Medycyna/Polska", odpowiedź: "Narodowy Fundusz Zdrowia" },
  { pytanie: "Jakie zwierzęta według przysłowia drzemy, kłócąc się z kimś?", kategoria: "Przysłowia", odpowiedź: "Koty" },
  { pytanie: "Jak nazywał się pierwszy prezydent USA?", kategoria: "Historia", odpowiedź: "Jerzy Waszyngton" },
  { pytanie: "Którego dnia maja obchodzony jest Dzień Flagi Rzeczypospolitej Polskiej?", kategoria: "Obyczaje/Polska", odpowiedź: "2 maja" },
  { pytanie: "LAN to sieć lokalna czy globalna?", kategoria: "Informatyka", odpowiedź: "Lokalna" },
  { pytanie: "Ile wynosi kadencja Parlamentu Europejskiego?", kategoria: "Polityka", odpowiedź: "5 lat" },
  { pytanie: "Jak nazywa się jednostka czasu w układzie SI?", kategoria: "Fizyka", odpowiedź: "Sekunda" },
  { pytanie: "Jak nazywa się główny plac w Wenecji?", kategoria: "Geografia", odpowiedź: "Plac św. Marka" },
  { pytanie: "Ile litrów krwi ma przeciętnie człowiek: 3, 5 czy 10?", kategoria: "Medycyna/Anatomi", odpowiedź: "5" },
  { pytanie: "Alfa, beta, gamma to początkowe litery którego alfabetu?", kategoria: "Językoznawstwo", odpowiedź: "Greckiego" },
  { pytanie: "Jak nazywa się najwyższy szczyt polskich Bieszczad?", kategoria: "Geografia Polski", odpowiedź: "Tarnica" },
  { pytanie: "Jak nazywa się niższa izba brytyjskiego parlamentu?", kategoria: "Polityka/Świat", odpowiedź: "Izba Gmin" },
  { pytanie: "Jak nazywa się pszczela rodzina wraz z jej otoczeniem?", kategoria: "Przyroda", odpowiedź: "Rój" },
  { pytanie: "Jakie imię nosił tęgi Gall, najlepszy przyjaciel Asterixa?", kategoria: "Komiks/Popkultura", odpowiedź: "Obeliks" },
  { pytanie: "Jak nazywa się wielki, pustynny obszar na terenie Mongolii i Chin?", kategoria: "Geografia", odpowiedź: "Pustynia Gobi" },
  { pytanie: "Jakie imię nosiła mityczna postać obdarowana przez Zeusa puszką zawierającą wszelkie nieszczęścia świata?", kategoria: "Mitologia", odpowiedź: "Pandora" },
  { pytanie: "W jakim kolorze jest liść klonu oznaczający w Polsce początkującego kierowcę?", kategoria: "Prawo drogowe", odpowiedź: "Zielonym" },
  { pytanie: "Z której strony świata według Biblii przybyli do Betlejem Trzej Królowie?", kategoria: "Religia", odpowiedź: "Ze wschodu" },
  { pytanie: "Co oznacza popularne angielskie określenie non-stop?", kategoria: "Język angielski", odpowiedź: "Bez przerwy" },
  { pytanie: "Ile wież łącznie stoi na szachownicy na początku partii?", kategoria: "Gry planszowe", odpowiedź: "Cztery" },
  { pytanie: "Jak nazywa się woda w stałym stanie skupienia?", kategoria: "Fizyka", odpowiedź: "Lód" },
  { pytanie: "Jak nazywa się miejsce na sali sądowej, gdzie zasiadają oskarżeni?", kategoria: "Prawo", odpowiedź: "Ława oskarżonych" },
  { pytanie: "Przez jakie 'h' piszemy słowo 'kontrahent'?", kategoria: "Ortografia", odpowiedź: "Przez 'h'" },
  { pytanie: "W którym mieście toczy się głównie akcja powieści 'Lalka' Bolesława Prusa?", kategoria: "Literatura", odpowiedź: "W Warszawie" },
  { pytanie: "Popularne w USA ciasto 'apple pie' to ciasto z którymi owocami?", kategoria: "Kulinaria", odpowiedź: "Z jabłkami" },
  { pytanie: "Jak nazywa się detektyw, którego przygody po raz pierwszy zostały opisane w książce 'Studium w szkarłacie'?", kategoria: "Literatura", odpowiedź: "Sherlock Holmes" },
  { pytanie: "Które miasto jest stolicą Kolumbii?", kategoria: "Geografia", odpowiedź: "Bogota" },
  { pytanie: "Jak u polskich górali nazywa się starszy pasterz, któremu podlegają juhasi?", kategoria: "Gwara/Kultura", odpowiedź: "Baca" },
  { pytanie: "Koralowce to zwierzęta czy rośliny?", kategoria: "Przyroda", odpowiedź: "Zwierzęta" },
  { pytanie: "Jakiego koloru są gwiazdy na fladze Unii Europejskiej?", kategoria: "Polityka/Flagi", odpowiedź: "Złotego (żółtego)" },
  { pytanie: "Do którego państwa należy obecnie miasto Lwów?", kategoria: "Geografia", odpowiedź: "Do Ukrainy" },
  { pytanie: "Papiloty to rodzaj butów na koturnie czy papierowe zwitki do robienia loków?", kategoria: "Inne", odpowiedź: "Papierowe zwitki do robienia loków" },
  { pytanie: "Który znak interpunkcyjny wyodrębnia w tekście cytaty?", kategoria: "Gramatyka", odpowiedź: "Cudzysłów" },
  { pytanie: "Kto był pierwszym przewodniczącym NSZZ 'Solidarność'?", kategoria: "Historia Polski", odpowiedź: "Lech Wałęsa" },
  { pytanie: "Kto jest autorem rewolucyjnego dzieła 'O obrotach sfer niebieskich'?", kategoria: "Nauka/Historia", odpowiedź: "Mikołaj Kopernik" },
  { pytanie: "Maltańczyki to rasa których popularnych zwierząt domowych?", kategoria: "Przyroda", odpowiedź: "Psów" },
  { pytanie: "Szkła w okularach, na które potocznie mówimy 'minusy', nosi krótkowidz czy dalekowidz?", kategoria: "Medycyna", odpowiedź: "Krótkowidz" },
  { pytanie: "Niemieccy bajkopisarze Jakub i Wilhelm Grimm byli ojcem i synem czy braćmi?", kategoria: "Literatura", odpowiedź: "Braćmi" },
  { pytanie: "W którym europejskim mieście znajduje się słynny uniwersytet o nazwie Sorbona?", kategoria: "Geografia", odpowiedź: "W Paryżu" },
  { pytanie: "Czym zajmuje się florysta?", kategoria: "Inne", odpowiedź: "Układaniem bukietów kwiatów" },
  { pytanie: "Jak nazywa się znak pieniężny wykonany z papieru?", kategoria: "Ekonomia", odpowiedź: "Banknot" },
  { pytanie: "Którego dnia marca obchodzony jest Międzynarodowy Dzień Kobiet?", kategoria: "Obyczaje", odpowiedź: "8 marca" },
  { pytanie: "Ile metrów mieści się w jednym kilometrze?", kategoria: "Matematyka/Metrologia", odpowiedź: "1000" },
  { pytanie: "Kto oprócz zawodników znajduje się bezpośrednio na ringu bokserskim w trakcie walki?", kategoria: "Sport", odpowiedź: "Sędzia" },
  { pytanie: "Czy dorsze żyją naturalnie w Morzu Bałtyckim?", kategoria: "Przyroda", odpowiedź: "Tak" },
  { pytanie: "Jaki język jest językiem urzędowym w Islandii?", kategoria: "Językoznawstwo", odpowiedź: "Islandzki" },
  { pytanie: "Jak nazywa się główny kościół diecezji, przy którym mieści się siedziba biskupa?", kategoria: "Religia", odpowiedź: "Katedra" },
  { pytanie: "Jak miał na imię roztargniony bohater wiersza Juliana Tuwima, który szukał swoich okularów?", kategoria: "Literatura", odpowiedź: "Hilary" },
  { pytanie: "Jak z francuskiego nazywa się nadwozie samochodu?", kategoria: "Technika/Język francuski", odpowiedź: "Karoseria" },
  { pytanie: "Czy Szczecin leży bezpośrednio nad otwartym Morzem Bałtyckim?", kategoria: "Geografia Polski", odpowiedź: "Nie" },
  { pytanie: "Brukselka to odmiana kapusty czy dyni?", kategoria: "Kulinaria/Przyroda", odpowiedź: "Kapusty" },
  { pytanie: "Jak nazywa się jadalnia dla załogi na statku?", kategoria: "Militaria/Inne", odpowiedź: "Mesa" },
  { pytanie: "Z kuchni którego państwa wywodzi się tradycyjne sushi?", kategoria: "Kulinaria", odpowiedź: "Z Japonii" },
  { pytanie: "Jak nazywa się w piosenkach powtarzający się po każdej zwrotce fragment tekstu i melodii?", kategoria: "Muzyka", odpowiedź: "Refren" },
  { pytanie: "Ile wokalistek wchodziło w skład szwedzkiego zespołu ABBA?", kategoria: "Muzyka", odpowiedź: "Dwie" },
  { pytanie: "Czy puchacz to gatunek sowy?", kategoria: "Przyroda", odpowiedź: "Tak" },
  { pytanie: "Jakiego koloru są z reguły kwiaty przebiśniegu?", kategoria: "Przyroda", odpowiedź: "Białe" },
  { pytanie: "Ar to jednostka długości czy powierzchni?", kategoria: "Matematyka/Metrologia", odpowiedź: "Powierzchni" },
  { pytanie: "Który tradycyjny kowalski wyrób według przesądu przynosi szczęście?", kategoria: "Obyczaje", odpowiedź: "Podkowa" },
  { pytanie: "Jakiego koloru są kwiaty żonkili?", kategoria: "Przyroda", odpowiedź: "Żółte" },
  { pytanie: "Szczypiorniści to sportowcy grający w piłkę nożną czy ręczną?", kategoria: "Sport", odpowiedź: "Ręczną" },
  { pytanie: "Jak brzmi stopień wyższy od przysłówka 'dobrze'?", kategoria: "Gramatyka", odpowiedź: "Lepiej" },
  { pytanie: "Czy do otrzymania prawa jazdy w Polsce potrzebne jest orzeczenie/zaświadczenie lekarskie?", kategoria: "Prawo", odpowiedź: "Tak" },
  { pytanie: "Ilu solistów występuje jednocześnie podczas recitalu?", kategoria: "Muzyka", odpowiedź: "Jeden" },
  { pytanie: "Z arkuszy papieru A2, A4 i A3, który ma najmniejsze wymiary?", kategoria: "Inne", odpowiedź: "A4" },
  { pytanie: "Czy w Polsce żyją na wolności kormorany?", kategoria: "Przyroda", odpowiedź: "Tak" },
  { pytanie: "Ile wynosi pierwiastek kwadratowy z liczby 64?", kategoria: "Matematyka", odpowiedź: "8" },
  { pytanie: "Czy wykrzyknik jest odmienną czy nieodmienną częścią mowy?", kategoria: "Gramatyka", odpowiedź: "Nieodmienną" },
  { pytanie: "Z kim tańcowała nitka w znanej bajce Jana Brzechwy?", kategoria: "Literatura", odpowiedź: "Z igłą" },
  { pytanie: "Co według popularnego powiedzenia 'kole w oczy'?", kategoria: "Przysłowia", odpowiedź: "Prawda" },
  { pytanie: "Jak miał na imię legendarny szwajcarski bohater Tell?", kategoria: "Literatura/Historia", odpowiedź: "Wilhelm" },
  { pytanie: "Proszę wymienić trzy główne gatunki (rodzaje) literackie.", kategoria: "Literatura", odpowiedź: "Liryka, epika, dramat" },
  { pytanie: "Co jest dłuższą jednostką długości: mila morska czy kilometr?", kategoria: "Metrologia/Geografia", odpowiedź: "Mila morska" },
  { pytanie: "Czy w Australii odbyły się kiedykolwiek letnie igrzyska olimpijskie?", kategoria: "Sport", odpowiedź: "Tak" },
  { pytanie: "Czy żyrafa należy do rzędu przeżuwaczy?", kategoria: "Przyroda", odpowiedź: "Tak" },
  { pytanie: "W którym polskim mieście znajduje się słynna Piernikowa Aleja Gwiazd?", kategoria: "Geografia Polski", odpowiedź: "W Toruniu" },
  { pytanie: "Jak nazywają się pierwsza i ostatnia litera alfabetu greckiego?", kategoria: "Językoznawstwo", odpowiedź: "Alfa i omega" },
  { pytanie: "Jak nazywa się stolica Rumunii?", kategoria: "Geografia", odpowiedź: "Bukareszt" },
  { pytanie: "Kto był twórcą kultowych postaci animowanych: Myszki Miki i psa Pluto?", kategoria: "Film/Kultura", odpowiedź: "Walt Disney" },
  { pytanie: "Czy osoba wyrażająca się kolokwialnie używa języka literackiego czy potocznego?", kategoria: "Język polski", odpowiedź: "Potocznego" },
  { pytanie: "Jakiego koloru jest pancerz najpospolitszej w Polsce biedronki?", kategoria: "Przyroda", odpowiedź: "Czerwonego" },
  { pytanie: "Zgodnie ze znanym powiedzeniem, kogo nie należy 'wywoływać z lasu'?", kategoria: "Przysłowia", odpowiedź: "Wilka" },
  { pytanie: "Sejsmologia to nauka zajmująca się badaniem jakich zjawisk?", kategoria: "Geografia/Nauka", odpowiedź: "Trzęsień ziemi" },
  { pytanie: "Kto zagrał tytułową rolę Jurka w kultowej komedii 'Kiler' Juliusza Machulskiego?", kategoria: "Film", odpowiedź: "Cezary Pazura" },
  { pytanie: "Pedant to człowiek przesadnie dokładny w działaniu czy nadmiernie oszczędny w wydatkach?", kategoria: "Język polski", odpowiedź: "Przesadnie dokładny" },
  { pytanie: "Nad którym oceanem leży państwo Chile?", kategoria: "Geografia", odpowiedź: "Nad Oceanem Spokojnym (Pacyfikiem)" },
  { pytanie: "Czy Polski Czerwony Krzyż (PCK) jest organizacją rządową?", kategoria: "Prawo/Inne", odpowiedź: "Nie (to organizacja pozarządowa)" },
  { pytanie: "W jakim języku starożytny poeta Wergiliusz napisał swój poemat 'Eneida'?", kategoria: "Literatura/Historia", odpowiedź: "W łacinie" },
  { pytanie: "Jak nazywa się karczma, w której rozgrywa się akcja ballady 'Pani Twardowska' Adama Mickiewicza?", kategoria: "Literatura", odpowiedź: "Rzym" },
  { pytanie: "Czy w skład tradycyjnej włoskiej potrawy o nazwie risotto wchodzi makaron?", kategoria: "Kulinaria", odpowiedź: "Nie (podstawą jest ryż)" },
  { pytanie: "O kim mówimy w słynnym powiedzeniu, że 'wstrzymał Słońce, ruszył Ziemię'?", kategoria: "Historia/Astronomia", odpowiedź: "O Mikołaju Koperniku" },
  { pytanie: "Kto spotkał w lesie siedmiu krasnoludków: Królewna Śnieżka czy Śpiąca Królewna?", kategoria: "Literatura", odpowiedź: "Królewna Śnieżka" },
  { pytanie: "Jak nazywamy człowieka, który znajduje satysfakcję i przyjemność w zadawaniu innym bólu fizycznego?", kategoria: "Inne", odpowiedź: "Sadysta" },
  { pytanie: "Kto jest autorem zarówno ballady 'Świteź', jak i ballady 'Świtezianka'?", kategoria: "Literatura", odpowiedź: "Adam Mickiewicz" },
  { pytanie: "Ktoś, o kim powiemy, że jest 'nie w ciemię bity', to człowiek sprytny czy naiwny?", kategoria: "Przysłowia", odpowiedź: "Sprytny" },
  { pytanie: "Jak nazywa się tytułowy bohater powieści Daniela Defoe, który spędził wiele lat na bezludnej wyspie?", kategoria: "Literatura", odpowiedź: "Robinson Crusoe" },
  { pytanie: "Jeśli jutro powiem, że jutro będzie czwartek, to jaki dzień tygodnia jest dzisiaj?", kategoria: "Logika", odpowiedź: "Wtorek" }
];

export const etap2: Pytanie[] = [
  {pytanie: "Jak nazywa się nielegalnie przemycony list do więzienia?", kategoria: "Prawo/Slang", odpowiedź: "Gryps" },
  { pytanie: "Paź królowej to gatunek których owadów?", kategoria: "Przyroda", odpowiedź: "Motyli" },
  { pytanie: "Czy z dna Morza Północnego jest wydobywana ropa naftowa?", kategoria: "Geografia/Gospodarka", odpowiedź: "Tak" },
  { pytanie: "Jaki bok trójkąta prostokątnego leży naprzeciw kąta prostego?", kategoria: "Matematyka", odpowiedź: "Przeciwprostokątna" },
  { pytanie: "Wielka Niedźwiedzica to gwiazdozbiór nieba północnego czy południowego?", kategoria: "Astronomia", odpowiedź: "Północnego" },
  { pytanie: "Czy w przypadku skrócenia kadencji Sejmu ulega skróceniu kadencja Senatu?", kategoria: "Prawo/Polityka", odpowiedź: "Tak" },
  { pytanie: "Która liczba jest mniejsza: -3/4 czy -1/3?", kategoria: "Matematyka", odpowiedź: "-3/4" },
  { pytanie: "Czy metro w Paryżu ma już ponad sto lat?", kategoria: "Inne", odpowiedź: "Tak, powstało w 1900 roku" },
  { pytanie: "Jak nazywa się krótką łopatkę żołnierską?", kategoria: "Militaria", odpowiedź: "Saperka" },
  { pytanie: "Nad którym oceanem leży Kenia?", kategoria: "Geografia", odpowiedź: "Oceanem Indyjskim" },
  { pytanie: "Którą dziedzinę sportu uprawia Felipe Massa?", kategoria: "Sport", odpowiedź: "Formuła 1" },
  { pytanie: "Kto w polskich siłach zbrojnych ma obecnie stopień Marszałka Polski?", kategoria: "Militaria", odpowiedź: "Nikt" },
  { pytanie: "Sikorsky S-61 to model amerykańskich myśliwców czy śmigłowców?", kategoria: "Militaria", odpowiedź: "Śmigłowców" },
  { pytanie: "Ile gwiazd widnieje na fladze Kuby?", kategoria: "Geografia/Flagi", odpowiedź: "Jedna" },
  { pytanie: "Jaki stosunek pokrewieństwa łączył Hektora i Parysa?", kategoria: "Mitologia", odpowiedź: "Byli braćmi" },
  { pytanie: "Z iloma państwami graniczy Mongolia?", kategoria: "Geografia", odpowiedź: "Z dwoma" },
  { pytanie: "Czy hektar należy do układu SI?", kategoria: "Fizyka/Metrologia", odpowiedź: "Nie należy" },
  { pytanie: "Które miasto leży bardziej na północ: Kopenhaga czy Helsinki?", kategoria: "Geografia", odpowiedź: "Helsinki" },
  { pytanie: "Jak nazywa się proces okresowego zrzucania skóry u płazów i gadów?", kategoria: "Przyroda", odpowiedź: "Linienie" },
  { pytanie: "Czy przedsiębiorcy mogą uzyskać dofinansowanie na realizację projektów związanych z agroturystyką?", kategoria: "Biznes/UE", odpowiedź: "Tak" },
  { pytanie: "Jak nazywał się klub sportowy, którego prezesem był Ryszard Ochódzki w filmie 'Miś'?", kategoria: "Film", odpowiedź: "KS Tęcza" },
  { pytanie: "Jak nazywa się jednostka natężenia dźwięku równa jednej dziesiątej bela?", kategoria: "Fizyka", odpowiedź: "Decybel" },
  { pytanie: "Czy liczbę wymierną można przedstawić w postaci ułamka zwykłego?", kategoria: "Matematyka", odpowiedź: "Tak" },
  { pytanie: "Z której wyspy uciekli Dedal i Ikar?", kategoria: "Mitologia", odpowiedź: "Z Krety" },
  { pytanie: "Czy Islandia jest republiką?", kategoria: "Geografia/Ustrój", odpowiedź: "Tak" },
  { pytanie: "Która liczba jest większa: milion milionów czy tysiąc miliardów?", kategoria: "Matematyka", odpowiedź: "Są równe" },
  { pytanie: "Czy wywodzące się z Polski konie huculskie są u nas hodowane?", kategoria: "Przyroda", odpowiedź: "Tak" },
  { pytanie: "Która rzeka jest dłuższa: Warta czy Narew?", kategoria: "Geografia Polski", odpowiedź: "Warta" },
  { pytanie: "Submarine to angielska nazwa jakiego rodzaju statku?", kategoria: "Język angielski/Militaria", odpowiedź: "Okrętu podwodnego" },
  { pytanie: "Mieszkańcy której planety dokonują inwazji na Ziemię w powieści H.G. Wellsa 'Wojna światów'?", kategoria: "Literatura", odpowiedź: "Marsa" },
  { pytanie: "Czy hokej na trawie jest dyscypliną olimpijską?", kategoria: "Sport", odpowiedź: "Tak" },
  { pytanie: "Niemiecka partia CDU to chrześcijańscy demokraci czy socjaliści?", kategoria: "Polityka", odpowiedź: "Chrześcijańscy demokraci" },
  { pytanie: "Który zwrotnik przechodzi przez Australię?", kategoria: "Geografia", odpowiedź: "Zwrotnik Koziorożca" },
  { pytanie: "Sekwoja to drzewo iglaste czy liściaste?", kategoria: "Przyroda", odpowiedź: "Iglaste" },
  { pytanie: "Jakiej narodowości był pierwszy zdobywca bieguna południowego Roald Amundsen?", kategoria: "Historia/Odkrycia", odpowiedź: "Norweskiej" },
  { pytanie: "Jak brzmi nazwa białego, sztywnego kartonu, która pochodzi od miasta w Anglii?", kategoria: "Inne", odpowiedź: "Bristol" },
  { pytanie: "Południki ziemskie określają długość czy szerokość geograficzną?", kategoria: "Geografia", odpowiedź: "Długość" },
  { pytanie: "Którą dyscyplinę sportu uprawiają Mariusz Fyrstenberg i Marcin Matkowski?", kategoria: "Sport", odpowiedź: "Tenis ziemny" },
  { pytanie: "Liderem którego zespołu jest Muniek Staszczyk?", kategoria: "Muzyka", odpowiedź: "T.Love" },
  { pytanie: "Czy Kazimierz Jagiellończyk był Wielkim Księciem Litewskim?", kategoria: "Historia Polski", odpowiedź: "Tak" },
  { pytanie: "Prolog to wprowadzenie do utworu czy też jego zakończenie?", kategoria: "Literatura", odpowiedź: "Wprowadzenie" },
  { pytanie: "Proszę podać przyimek w zdaniu: 'Przed szkołą stał autokar'?", kategoria: "Gramatyka", odpowiedź: "Przed" },
  { pytanie: "Który rozbiór Polski nastąpił w 1772 roku?", kategoria: "Historia Polski", odpowiedź: "Pierwszy" },
  { pytanie: "Jak nazywa się najwyższy głos męski?", kategoria: "Muzyka", odpowiedź: "Tenor" },
  { pytanie: "Jak nazywają się amerykańskie nagrody nazywane telewizyjnymi Oscarami?", kategoria: "Telewizja/Film", odpowiedź: "Emmy" },
  { pytanie: "Ukwiały należą do świata roślin czy zwierząt?", kategoria: "Przyroda", odpowiedź: "Do zwierząt" },
  { pytanie: "Który pedał w fortepianie służy do przedłużania dźwięków?", kategoria: "Muzyka", odpowiedź: "Prawy" },
  { pytanie: "Czy halibut jest rybą drapieżną?", kategoria: "Przyroda", odpowiedź: "Tak" },
  { pytanie: "Ile kadencji prezydentem USA był John F. Kennedy?", kategoria: "Historia", odpowiedź: "Niecałą jedną" },
  { pytanie: "Czy sztuczny jedwab jest wyrabiany z wiskozy?", kategoria: "Chemia/Przemysł", odpowiedź: "Tak" },
  { pytanie: "W jakim mieście powstał zespół 'The Beatles'?", kategoria: "Muzyka", odpowiedź: "W Liverpoolu" },
  { pytanie: "Na jakiej rzece znajduje się włocławski zbiornik wodny?", kategoria: "Geografia Polski", odpowiedź: "Na Wiśle" },
  { pytanie: "Jakie trzy instrumenty wchodzą w skład trio fortepianowego?", kategoria: "Muzyka", odpowiedź: "Fortepian, skrzypce, wiolonczela" },
  { pytanie: "Jak z angielskiego nazywa się w boksie zwarcie?", kategoria: "Sport/Język angielski", odpowiedź: "Klincz" },
  { pytanie: "Taśma barwiąca występuje w drukarce igłowej czy laserowej?", kategoria: "Technika/Informatyka", odpowiedź: "W drukarce igłowej" },
  { pytanie: "Jakiego koloru dziób ma bocian czarny?", kategoria: "Przyroda", odpowiedź: "Czerwonego" },
  { pytanie: "Kształt jakiej figury geometrycznej mają zazwyczaj łazanki?", kategoria: "Kulinaria", odpowiedź: "Kwadratu lub prostokąta" },
  { pytanie: "Czy każdy pierwiastek posiada swoje izotopy?", kategoria: "Chemia/Fizyka", odpowiedź: "Tak" },
  { pytanie: "Jak przedrimek/przedrostek nosi jedna dziesiąta (1/10) jakiejś wielkości?", kategoria: "Metrologia", odpowiedź: "Decy" },
  { pytanie: "Drużyna którego kraju w piłce nożnej jest zwyczajowo określana jako 'Pomarańczowi'?", kategoria: "Sport", odpowiedź: "Holandii" },
  { pytanie: "Jak nazywa się samolot przystosowany do startowania i lądowania na wodzie?", kategoria: "Technika", odpowiedź: "Hydroplan" },
  { odpowiedź: "W Warszawie", kategoria: "Film/Historia", pytanie: "W którym mieście rozgrywa się akcja filmu 'Pianista'?" },
  { pytanie: "Jakiego rodzaju pod względem kształtu jest nasza Galaktyka (Droga Mleczna)?", kategoria: "Astronomia", odpowiedź: "Spiralna" },
  { pytanie: "Jakie dwa języki są urzędowymi w Finlandii?", kategoria: "Geografia/Języki", odpowiedź: "Fiński i szwedzki" },
  { pytanie: "Jak nazywał się dowódca obrony Westerplatte w 1939 roku?", kategoria: "Historia Polski", odpowiedź: "mjr Henryk Sucharski" },
  { pytanie: "Który stan USA nosi taką samą nazwę w języku angielskim jak kaukaskie państwo Gruzja?", kategoria: "Geografia", odpowiedź: "Georgia" },
  { pytanie: "Ilu członków Krajowej Rady Radiofonii i Telewizji mianuje Senat?", kategoria: "Prawo/Polska", odpowiedź: "Jednego" },
  { pytanie: "Na którym kontynencie znajdują się góry Notre Dame?", kategoria: "Geografia", odpowiedź: "W Ameryce Północnej" },
  { pytanie: "Czy Mahomet, twórca islamu, miał żonę?", kategoria: "Religia", odpowiedź: "Tak (miał ich kilka, pierwszą była Chadidża)" },
  { pytanie: "Czy do strefy Schengen należą wyłącznie kraje będące członkami Unii Europejskiej?", kategoria: "Polityka", odpowiedź: "Nie (należą też np. Szwajcaria, Norwegia, Islandia)" },
  { pytanie: "Na terenie którego województwa leży w całości Kampinoski Park Narodowy?", kategoria: "Geografia Polski", odpowiedź: "Mazowieckiego" },
  { pytanie: "Jakie wino powstaje najczęściej ze szczepu winogron Cabernet Sauvignon: czerwone czy białe?", kategoria: "Kulinaria", odpowiedź: "Czerwone" },
  { pytanie: "Kogo żołnierze Legionów Polskich nazywali potocznie 'Dziadkiem'?", kategoria: "Historia Polski", odpowiedź: "Józefa Piłsudskiego" },
  { pytanie: "Czy przekątne każdego deltoidu są względem siebie prostopadłe?", kategoria: "Matematyka", odpowiedź: "Tak" },
  { pytanie: "Jaki pseudonim nosił słynny żołnierz Szarych Szeregów Tadeusz Zawadzki, bohater 'Kamieni na szaniec'?", kategoria: "Historia Polski", odpowiedź: "Zośka" },
  { pytanie: "Czy owoc papai ma w środku tylko jedną, dużą pestkę?", kategoria: "Przyroda", odpowiedź: "Nie (ma bardzo wiele drobnych pestek)" },
  { pytanie: "Mydło pod względem chemicznym jest alkoholem, estrem czy solą?", kategoria: "Chemia", odpowiedź: "Solą (solą wyższych kwasów tłuszczowych)" },
  { pytanie: "Nad jakim jeziorem leży szwajcarskie miasto Lozanna?", kategoria: "Geografia", odpowiedź: "Nad Jeziorem Genewskim" },
  { pytanie: "Flaga którego państwa, oprócz brytyjskiego Union Jacka, zawiera również konstelację Krzyża Południa?", kategoria: "Geografia/Flagi", odpowiedź: "Australii" },
  { pytanie: "W którym roku odbyły się w Atenach pierwsze nowożytne igrzyska olimpijskie?", kategoria: "Sport/Historia", odpowiedź: "1896" },
  { pytanie: "Które trzy powieści Henryka Sienkiewicza tworzą jego słynną Trylogię?", kategoria: "Literatura", odpowiedź: "'Ogniem i mieczem', 'Potop', 'Pan Wołodyjowski'" },
  { pytanie: "Lituanistyka to nauka o literaturze, historii i języku którego kraju?", kategoria: "Nauka", odpowiedź: "Litwy" },
  { pytanie: "Który nosorożec posiada dwa rogi: zwyczajny (afrykański) czy indyjski?", kategoria: "Przyroda", odpowiedź: "Zwyczajny (indyjski ma jeden)" },
  { pytanie: "Kto w tekście 'Mazurka Dąbrowskiego' dał Polakom przykład, jak mają zwyciężać?", kategoria: "Historia/Literatura", odpowiedź: "Napoleon Bonaparte" },
  { pytanie: "Jeśli mianownik brzmi 'oboje rodzice', to jak brzmi ten zwrot w dopełniaczu?", kategoria: "Język polski", odpowiedź: "Obojga rodziców" },
  { pytanie: "Tzw. suchy lód to stała postać którego związku chemicznego?", kategoria: "Chemia/Fizyka", odpowiedź: "Dwutlenku węgla" },
  { pytanie: "W którym mieście hiszpańskim piłkarze Realu grają na stadionie Santiago Bernabéu?", kategoria: "Sport", odpowiedź: "W Madrycie" },
  { pytanie: "Czy wykresem funkcji liniowej w układzie współrzędnych może być hiperbola?", kategoria: "Matematyka", odpowiedź: "Nie (wykresem jest prosta)" },
  { pytanie: "Jak nazywa się elektroda połączona z ujemnym biegunem źródła prądu stałego?", kategoria: "Fizyka/Chemia", odpowiedź: "Katoda" },
  { pytanie: "Kto w Rzeczypospolitej Polskiej oficjalnie powołuje sędziów na wniosek KRS?", kategoria: "Prawo/Polska", odpowiedź: "Prezydent RP" },
  { pytanie: "Współcześnie żyjący sfinks (oprócz mitycznego stworzenia) to rasa którego zwierzęcia domowego?", kategoria: "Przyroda", odpowiedź: "Kota" },
  { pytanie: "Jak inaczej w chemii i przemyśle nazywa się trójnitrotoluen (TNT)?", kategoria: "Chemia", odpowiedź: "Trotyl" },
  { pytanie: "Które dwie planety naszego Układu Słonecznego nie posiadają ani jednego naturalnego satelity?", kategoria: "Astronomia", odpowiedź: "Merkury i Wenus" },
  { pytanie: "Znak rejestracyjny 'SP' umieszczony na kadłubie oznacza przynależność statku powietrznego do którego państwa?", kategoria: "Technika/Świat", odpowiedź: "Do Polski" },
  { pytanie: "Jak potocznie nazywa się tradycyjny album przeznaczony do kolekcjonowania znaczków pocztowych?", kategoria: "Inne", odpowiedź: "Klaser" },
  { pytanie: "Który kluczowy organ ludzkiego ciała mieści się bezpośrednio w worku osierdziowym?", kategoria: "Medycyna/Anatomia", odpowiedź: "Serce" },
  { pytanie: "Monsun to wiatr stały czy sezonowy?", kategoria: "Geografia/Meteorologia", odpowiedź: "Sezonowy" },
  { pytanie: "Ile kątów prostych może mieć maksymalnie jeden trójkąt na płaszczyźnie?", kategoria: "Matematyka", odpowiedź: "Jeden" },
  { pytanie: "Au to symbol chemiczny którego cennego pierwiastka?", kategoria: "Chemia", odpowiedź: "Złota" },
  { pytanie: "Iluizbowy strukturalnie jest Parlament Europejski?", kategoria: "Polityka", odpowiedź: "Jednoizbowy" },
  { pytanie: "Z jakich roślinnych płodów ziemi wytwarzany jest spożywczy olej arachidowy?", kategoria: "Kulinaria", odpowiedź: "Z orzeszków ziemnych (arachidowych)" },
  { pytanie: "Czy minerał o nazwie kalcyt jest samodzielnym pierwiastkiem chemicznym?", kategoria: "Chemia/Geologia", odpowiedź: "Nie (to węglan wapnia)" },
  { pytanie: "Ile atomów wodoru znajduje się w jednej cząsteczce amoniaku ($NH_3$)?", kategoria: "Chemia", odpowiedź: "Trzy" },
  { pytanie: "Jak nazywamy osobę, która bezprawnie i samowolnie przywłaszcza sobie najwyższą władzę lub stanowisko?", kategoria: "Prawo/Polityka", odpowiedź: "Uzurpator" },
  { pytanie: "Podstawowym surowcem do wyrobu narzędzi w epoce paleolitu była cyna, miedź czy kamień?", kategoria: "Historia/Archeologia", odpowiedź: "Kamień" },
  { pytanie: "W którym roku zbrojnie rozpoczął się w historii Polski tzw. potop szwedzki?", kategoria: "Historia Polski", odpowiedź: "1655" },
  { pytanie: "Jak nazywają się dwie izby współczesnego parlamentu francuskiego?", kategoria: "Polityka/Świat", odpowiedź: "Zgromadzenie Narodowe i Senat" },
  { pytanie: "W którym państwie europejskim (oprócz Federacji Rosyjskiej) oficjalną walutą narodową jest rubel?", kategoria: "Geografia/Ekonomia", odpowiedź: "Na Białorusi" },
  { pytanie: "Anatolia to historyczna, azjatycka część którego współczesnego państwa?", kategoria: "Geografia", odpowiedź: "Turcji" },
  { pytanie: "Jaką nazwę, pochodzącą bezpośrednio od imienia swojego założyciela, nosi katolicki Zakon Braci Mniejszych?", kategoria: "Religia", odpowiedź: "Franciszkanie" },
  { pytanie: "Na terenie którego parku narodowego w Polsce wznosi się licznie odwiedzany Kasprowy Wierch?", kategoria: "Geografia Polski", odpowiedź: "Tatrzańskiego Parku Narodowego" },
  { pytanie: "Jak nazywa się krzywa stożkowa, która jest geometrycznym wykresem funkcji kwadratowej?", kategoria: "Matematyka", odpowiedź: "Parabola" },
  { pytanie: "W którym państwie Ameryki Południowej rozgrywa się główna akcja słynnego musicalu 'Evita'?", kategoria: "Muzyka/Film", odpowiedź: "W Argentynie" },
  { pytanie: "Jak nazywa się jednoczesny wystrzał z wielu karabinów lub armat?", kategoria: "Militaria", odpowiedź: "Salwa" },
  { pytanie: "Czy oranżeria to dokładnie to samo co pomarańczarnia?", kategoria: "Język polski/Inne", odpowiedź: "Tak" }, // Skorygowałem z "Nie", bo synonimicznie to te same obiekty (ogrody zimowe)
  { pytanie: "Na którym kontynencie leży państwo Brunei?", kategoria: "Geografia", odpowiedź: "W Azji" },
  { pytanie: "Czy dziobak posiada ogon?", kategoria: "Przyroda", odpowiedź: "Tak" },
  { pytanie: "Które zwierzę oplatało laskę Asklepiosa – boga sztuki lekarskiej?", kategoria: "Mitologia/Medycyna", odpowiedź: "Wąż" },
  { pytanie: "Czy neutrony posiadają ładunek elektryczny dodatni?", kategoria: "Fizyka", odpowiedź: "Nie (są obojętne elektrycznie)" },
  { pytanie: "Włoski przysmak panna cotta to rodzaj napoju, dania mięsnego czy deseru?", kategoria: "Kulinaria", odpowiedź: "Deseru" },
  { pytanie: "Jaki kolor ma stoliczek w znanej dziecięcej wyliczance 'Entliczek, pentliczek'?", kategoria: "Literatura", odpowiedź: "Czerwony" },
  { pytanie: "Czy wyroki Trybunału Sprawiedliwości UE są wiążące dla sądów państw członkowskich?", kategoria: "Prawo", odpowiedź: "Tak" },
  { pytanie: "Czy popularne cyrkonie używane w biżuterii to kamienie szlachetne?", kategoria: "Inne", odpowiedź: "Nie (to syntetyczne kryształy)" },
  { pytanie: "Proszę rozwinąć skrót urzędu statystycznego powstałego w 1918 roku: GUS.", kategoria: "Polska", odpowiedź: "Główny Urząd Statystyczny" },
  { pytanie: "Który polski bramkarz zasłynął 'zatrzymaniem Anglii' na stadionie Wembley w 1973 roku?", kategoria: "Sport", odpowiedź: "Jan Tomaszewski" },
  { pytanie: "Jaki symbol chemiczny w układzie okresowym ma ołów?", kategoria: "Chemia", odpowiedź: "Pb" },
  { pytanie: "Liczby 1, 2, 3 – która z nich w świetle definicji matematycznej NIE jest liczbą pierwszą?", kategoria: "Matematyka", odpowiedź: "1" },
  { pytanie: "Jak nazywa się bierna, niekurczliwa część mięśnia, która przytwierdza go do kości?", kategoria: "Medycyna/Anatomia", odpowiedź: "Ścięgno" },
  { pytanie: "Jaki ładunek elektryczny posiada pozyton (antycząstka elektronu)?", kategoria: "Fizyka", odpowiedź: "Dodatni" },
  { pytanie: "Którą dyscyplinę sportu uprawiali bracia Witalij i Władymir Kliczko?", kategoria: "Sport", odpowiedź: "Boks" },
  { pytanie: "Czy w medycynie i biologii znana jest witamina H?", kategoria: "Medycyna", odpowiedź: "Tak (to inaczej witamina B7 lub biotyna)" },
  { pytanie: "Proszę rozwinąć skrót polskiej organizacji ratunkowej GOPR.", kategoria: "Polska", odpowiedź: "Górskie Ochotnicze Pogotowie Ratunkowe" },
  { pytanie: "W dziecięcej wyliczance 'Kipi kasza, kipi groch...', co według tekstu okazuje się lepsze?", kategoria: "Literatura", odpowiedź: "Kasza" },
  { pytanie: "W której części Gdańska leży zabytkowa katedra ze słynnymi organami zbudowanymi m.in. przez Jana Wulfa?", kategoria: "Geografia Polski/Sztuka", odpowiedź: "W Oliwie" },
  { pytanie: "Moda i ubiory: jak nazywa się tradycyjny strój górali szkockich mający formę spódniczki w kratę?", kategoria: "Obyczaje", odpowiedź: "Kilt" },
  { pytanie: "Ludzkie ciało pod względem fizycznym przewodzi elektryczność czy jest całkowitym izolatorem?", kategoria: "Fizyka/Medycyna", odpowiedź: "Przewodzi" },
  { pytanie: "W jakim kolorze jest charakterystyczny wzór krzyża na grzbiecie pająka krzyżaka?", kategoria: "Przyroda", odpowiedź: "W białym" },
  { pytanie: "Rotunda to budowla wzniesiona na planie koła czy krzyża?", kategoria: "Architektura", odpowiedź: "Na planie koła" },
  { pytanie: "Planimetria jako dział geometrii zajmuje się figurami płaskimi czy przestrzennymi?", kategoria: "Matematyka", odpowiedź: "Płaskimi" },
  { pytanie: "Jak nazywa się kostka w domino, która nie zawiera żadnych kropek (ma puste pola)?", kategoria: "Gry planszowe", odpowiedź: "Mydło" },
  { pytanie: "Litera 'H' umieszczona na tablicy rejestracyjnej w międzynarodowym ruchu samochodowym to skrót którego państwa?", kategoria: "Świat/Inne", odpowiedź: "Węgier" },
  { pytanie: "Kto zagrał kultową rolę 'Kobiety Pracującej' w serialu 'Czterdziestolatek'?", kategoria: "Film", odpowiedź: "Irena Kwiatkowska" },
  { pytanie: "Jak z francuskiego potocznie nazywamy bogato ilustrowane czasopismo poświęcone modzie?", kategoria: "Język francuski/Inne", odpowiedź: "Żurnal" },
  { pytanie: "Jak nazywa się tworzony co roku dokument planu przewidywanych wydatków i przychodów państwa?", kategoria: "Ekonomia/Polityka", odpowiedź: "Budżet" },
  { pytanie: "Kto napisał słynną powieść pozytywistyczną 'Nad Niemnem'?", kategoria: "Literatura", odpowiedź: "Eliza Orzeszkowa" },
  { pytanie: "Jarmuż to tradycyjne danie ukraińskie, jadalna roślina czy element stroju chasydów?", kategoria: "Kulinaria/Przyroda", odpowiedź: "Roślina" },
  { pytanie: "Jeśli napięcie w obwodzie wynosi 100 V, a natężenie prądu 2 A, to ile wynosi opór zgodnie z prawem Ohma?", kategoria: "Fizyka", odpowiedź: "50 omów" },
  { pytanie: "Gallicyzmy to w językoznawstwie zapożyczenia pochodzące z którego języka?", kategoria: "Językoznawstwo", odpowiedź: "Z francuskiego" },
  { pytanie: "Kto jest wykonawcą poruszającej piosenki 'Tańczące Eurydyki'?", kategoria: "Muzyka", odpowiedź: "Anna German" },
  { pytanie: "Który rzymski władca w 44 roku p.n.e. został zasztyletowany przez spiskowców w rzymskim Senacie?", kategoria: "Historia", odpowiedź: "Juliusz Cezar" },
  { pytanie: "Jak nazywa się wydział na uczelni wyższej obejmujący studia nad językiem i literaturą obszaru dawnego Albionu?", kategoria: "Językoznawstwo", odpowiedź: "Filologia angielska (anglistyka)" },
  { pytanie: "Kto jest autorem słynnych polskich obrazów realistycznych 'Bociany' oraz 'Żurawie'?", kategoria: "Sztuka", odpowiedź: "Józef Chełmoński" },
  { pytanie: "Sporady Południowe to archipelag wysp należący do Włoch czy do Grecji?", kategoria: "Geografia", odpowiedź: "Do Grecji" },
  { pytanie: "Jak nazywa się kopalnia węgla kamiennego w Katowicach, w której w grudniu 1981 roku pacyfikacja strajku doprowadziła do śmierci 9 górników?", kategoria: "Historia Polski", odpowiedź: "KWK Wujek" },
  { pytanie: "Które zwierzę jest tradycyjnym symbolem bessy (spadków) na giełdzie papierów wartościowych?", kategoria: "Ekonomia", odpowiedź: "Niedźwiedź" },
  { pytanie: "Na którym kontynencie w przeważającej części rozciąga się pustynia Gobi?", kategoria: "Geografia", odpowiedź: "W Azji" },
  { pytanie: "Jak nazywa się okres sprawowania funkcji oraz godności przez papieża? Słowo to pochodzi z łaciny.", kategoria: "Religia/Język łaciński", odpowiedź: "Pontyfikat" },
  { pytanie: "W którym roku podczas II wojny światowej miała miejsce przełomowa na Pacyfiku bitwa o Midway?", kategoria: "Historia", odpowiedź: "In 1942" },
  { pytanie: "Muł to bezpłodna krzyżówka których dwóch gatunków zwierząt?", kategoria: "Przyroda", odpowiedź: "Konia i osła" },
  { pytanie: "Czy we współczesnej Polsce prezydent RP wybierany jest bezpośrednio przez parlament?", kategoria: "Prawo/Polska", odpowiedź: "Nie (wybierany jest w wyborach powszechnych przez obywateli)" },
  { pytanie: "Jak nazywał się sztywny kapelusz męski o półkolistej główce i wąskim rondzie, niezwykle modny w drugiej połowie XIX wieku?", kategoria: "Obyczaje/Moda", odpowiedź: "Melonik" },
  { pytanie: "W rocznicę wyzwolenia którego niemieckiego obozu koncentracyjnego przypada Międzynarodowy Dzień Pamięci o Ofiarach Holocaustu?", kategoria: "Historia", odpowiedź: "Auschwitz (Auschwitz-Birkenau)" },
  { pytanie: "Czy w nomenklaturze fizycznej i elektrotechnicznej 'opornik' i 'rezystor' to dokładnie to samo urządzenie?", kategoria: "Fizyka/Technika", odpowiedź: "Tak" },
  { pytanie: "Która polska wokalistka nagrała w latach 80. wielki hit 'Malinowy król' wspólnie z zespołem Budka Suflera?", kategoria: "Muzyka", odpowiedź: "Urszula" },
  { pytanie: "Czy na terenie Polski oficjalnie działa międzynarodowa organizacja praw człowieka Amnesty International?", kategoria: "Prawo/Świat", odpowiedź: "Tak" },
  { pytanie: "Nad którym oceanem leży amerykański stan Kalifornia?", kategoria: "Geografia", odpowiedź: "Nad Oceanem Spokojnym (Pacyfikiem)" },
  { pytanie: "Jak nazywała się legendarna, złota kraina w Ameryce Południowej, namiętnie poszukiwana przez hiszpańskich konkwistadorów?", kategoria: "Historia", odpowiedź: "Eldorado" },
  { pytanie: "Z którego europejskiego kraju pochodziła pisarka Karen Blixen, autorka głośnej powieści 'Pożegnanie z Afryką'?", kategoria: "Literatura", odpowiedź: "Z Danii" },
  { pytanie: "Słynne dzieło 'Boska komedia' Dantego Alighieri zostało oryginalnie napisane prozą czy wierszem?", kategoria: "Literatura", odpowiedź: "Wierszem" },
  { pytanie: "Jakie imię nosi piękna Cyganka, tytułowa bohaterka słynnej opery Georgesa Bizeta?", kategoria: "Muzyka/Sztuka", odpowiedź: "Carmen" },
  { pytanie: "Z których dwóch podstawowych składników przygotowywany jest tradycyjny przaśny chleb żydowski – maca?", kategoria: "Kulinaria/Religia", odpowiedź: "Z mąki i wody" },
  { pytanie: "Na którym kontynencie leży państwo Sudan?", kategoria: "Geografia", odpowiedź: "W Afryce" },
  { pytanie: "Jaką biologiczną nazwę nosi ogół drobnych organizmów roślinnych i zwierzęcych unoszących się biernie w wodzie?", kategoria: "Przyroda", odpowiedź: "Plankton" },
  { pytanie: "W jakich jednostkach tradycyjnie mierzy się prędkość poruszania się jednostek w żegludze morskiej?", kategoria: "Metrologia/Inne", odpowiedź: "W węzłach" },
  { pytanie: "Z kuchni którego bliskowschodniego państwa pierwotnie wywodzi się popularny na całym świecie kebab?", kategoria: "Kulinaria", odpowiedź: "Z Turcji" },
  { pytanie: "Jakim wspólnym mianem określa się w Nowym Testamencie dwunastu najbliższych uczniów Jezusa Chrystusa?", kategoria: "Religia", odpowiedź: "Apostołowie" },
  { pytanie: "Która część ciała, według mitologii greckiej, była jedynym i śmiertelnym słabym punktem Achillesa?", kategoria: "Mitologia", odpowiedź: "Pięta" },
  { pytanie: "Przez ile miesięcy w roku kalendarzowym obowiązuje obecnie w Polsce tak zwany czas zimowy?", kategoria: "Inne", odpowiedź: "5 miesięcy" },
  { pytanie: "Kwas mlekowy, powstający m.in. w mięśniach podczas wysiłku, to związek chemiczny organiczny czy nieorganiczny?", kategoria: "Chemia/Medycyna", odpowiedź: "Organiczny" },
  { pytanie: "Czy Borys Godunow, tytułowy bohater dramatu Aleksandra Puszkina, był postacią historyczną?", kategoria: "Historia/Literatura", odpowiedź: "Tak (był carem Rosji)" },
  { pytanie: "Synogarlice, ptaki powszechnie występujące w miastach, to odmiana dzikich gołębi czy sikorek?", kategoria: "Przyroda", odpowiedź: "Gołębi" },
  { pytanie: "Jakie dwa kolory widnieją na oficjalnej fladze państwowej Arabii Saudyjskiej?", kategoria: "Świat", odpowiedź: "Zielony i biały" },
  { pytanie: "Jak profesjonalnie nazywa się czynność rolnicza lub leśna polegająca na usuwaniu z ziemi pni i korzeni ściętych drzew?", kategoria: "Inne", odpowiedź: "Karczowanie" },
  { pytanie: "Szombierki to historyczna i przemysłowa dzielnica którego śląskiego miasta?", kategoria: "Geografia Polski", odpowiedź: "Bytomia" },
  { pytanie: "Jaki jest oficjalny symbol chemiczny krzemu w układzie okresowym pierwiastków?", kategoria: "Chemia", odpowiedź: "Si" }
]

export const final: Pytanie[] = [
  { pytanie: "Która aktorka grała główną rolę w filmie Sydneya Pollacka 'Pożegnanie z Afryką'?", kategoria: "Film", odpowiedź: "Meryl Streep" },
  { pytanie: "Czy sasanka zwyczajna jest w Polsce pod ochroną?", kategoria: "Przyroda/Botanika", odpowiedź: "Nie (jest gatunkiem wymarłym w naturze)" },
  { pytanie: "W której dolinie w Tatrach leży jezioro Zadni Staw Polski?", kategoria: "Geografia Polski", odpowiedź: "W Dolinie Pięciu Stawów Polskich" },
  { pytanie: "Jak nazywa się choroba polegająca na złym widzeniu przy słabym świetle?", kategoria: "Medycyna", odpowiedź: "Kurza ślepota (nyktalopia)" },
  { pytanie: "Jak nazywamy płatnego partnera do tańca w lokalach rozrywkowych?", kategoria: "Inne", odpowiedź: "Żigolo" },
  { pytanie: "Jakiego koloru była herbowa róża Lancasterów?", kategoria: "Historia", odpowiedź: "Czerwona" },
  { pytanie: "W którym roku do Czechosłowacji wkroczyły wojska Układu Warszawskiego?", kategoria: "Historia", odpowiedź: "1968" },
  { pytanie: "Jakiej narodowości był Willem Barents, który odkrył Spitsbergen?", kategoria: "Historia/Odkrycia", odpowiedź: "Holenderskiej" },
  { pytanie: "Który wódz Hunów zwany był Biczem Bożym?", kategoria: "Historia", odpowiedź: "Attyla" },
  { pytanie: "Czy katolickich księży obowiązuje obecnie tonsura?", kategoria: "Religia", odpowiedź: "Nie (zniesiono ją po Soborze Watykańskim II)" },
  { pytanie: "Jak nazywał się rosyjski fizjolog, który wprowadził pojęcie odruchów warunkowych?", kategoria: "Nauka", odpowiedź: "Iwan Pawłow" },
  { pytanie: "Ile armat miała reduta Ordona w wierszu A. Mickiewicza?", kategoria: "Literatura", odpowiedź: "6" },
  { pytanie: "Jaka jest nazwa jednej z najwyższych zapór wodnych świata na rzece Kolorado?", kategoria: "Geografia", odpowiedź: "Tama Hoovera" },
  { pytanie: "Sublimat to chlorek którego metalu?", kategoria: "Chemia", odpowiedź: "Rtęci" },
  { pytanie: "Co zabiera Wenus więcej czasu: obieg dookoła Słońca czy obrót dookoła osi?", kategoria: "Astronomia", odpowiedź: "Obrót dookoła osi" },
  { pytanie: "Kto jest autorem wiersza 'Wspomnienie', który śpiewał Czesław Niemen?", kategoria: "Literatura/Muzyka", odpowiedź: "Julian Tuwim" },
  { pytanie: "Proszę dokończyć powiedzenie hetmana Czarnieckiego: 'Ja nie z soli, ani z roli...'?", kategoria: "Historia/Cytaty", odpowiedź: '...ale z tego, co mnie boli, wyrosłem' },
  { pytanie: "Jak nazywał się właściciel cukierni w Krakowie, w której działał kabaret Zielony Balonik?", kategoria: "Historia/Kultura", odpowiedź: "Apolinary Jan Michalik (Michalikowa Jama)" },
  { pytanie: "Sasza, Pchełka i Anita to bohaterowie której sztuki Janusza Głowackiego?", kategoria: "Teatr/Literatura", odpowiedź: "Antygona w Nowym Jorku" },
  { pytanie: "Na ogonie którego ptaka Hera umieściła oczy Argosa?", kategoria: "Mitologia", odpowiedź: "Pawia" },
  { pytanie: "Jak w muzyce nazywa się wykonanie utworu z nut bez przygotowania?", kategoria: "Muzyka", odpowiedź: "A vista" },
  { pytanie: "Jak z hebrajskiego nazywa się pałeczka do śledzenia czytanego wersetu Tory?", kategoria: "Religia/Kultura", odpowiedź: "Jad" },
  { pytanie: "Która kategoria wagowa w boksie jest cięższa: musza czy kogucia?", kategoria: "Sport", odpowiedź: "Kogucia" },
  { pytanie: "Kto objawił się Kleofasowi i Szymonowi Piotrowi na drodze do Emaus?", kategoria: "Religia", odpowiedź: "Jezus" },
  { pytanie: "Ile typów ludzkich temperamentów wyróżnił Hipokrates?", kategoria: "Medycyna/Psychologia", odpowiedź: "4" },
  { pytanie: "Które miasto Ukrainy jest znane z Schodów Potiomkinowskich?", kategoria: "Geografia", odpowiedź: "Odessa" },
  { pytanie: "Proszę podać oba imiona pana Zagłoby z Trylogii Sienkiewicza?", kategoria: "Literatura", odpowiedź: "Jan Onufry" },
  { pytanie: "Etna, Stromboli, Tambora – który z tych wulkanów nie wznosi się we Włoszech?", kategoria: "Geografia", odpowiedź: "Tambora (w Indonezji)" },
  { pytanie: "Która choroba przenoszona przez pchły zabiła trzecią część Europy w XIV wieku?", kategoria: "Historia/Medycyna", odpowiedź: "Dżuma" },
  { pytanie: "Z których pierwiastków zbudowana jest cząsteczka skrobi?", kategoria: "Chemia", odpowiedź: "Węgla, wodoru i tlenu" },
  { pytanie: "Jaki przydomek nosiła królowa Maria I Tudor?", kategoria: "Historia", odpowiedź: "Krwawa Mary (Bloody Mary)" },
  { pytanie: "Która organizacja przejęła majątek rozwiązanej w 1946 roku Ligi Narodów?", kategoria: "Historia/Polityka", odpowiedź: "ONZ" },
  { pytanie: "Jak nazywał się założyciel klasztoru franciszkanów w Niepokalanowie?", kategoria: "Religia/Historia Polski", odpowiedź: "Maksymilian Maria Kolbe" },
  { pytanie: "Jak nazywa się artysta rzeźbiący w drewnie (słowo pochodzi z niemieckiego)?", kategoria: "Sztuka", odpowiedź: "Snycerz" },
  { pytanie: "Gaz rozweselający to potoczna nazwa podtlenku którego pierwiastka?", kategoria: "Chemia", odpowiedź: "Azotu" },
  { pytanie: "Zaprzysiężenie którego polskiego prezydenta zakończyło misję rządu na uchodźstwie?", kategoria: "Historia Polski", odpowiedź: "Lecha Wałęsy" },
  { pytanie: "Jak nazywa się amerykańska aktorka, siostra Warrena Beatty'ego?", kategoria: "Film", odpowiedź: "Shirley MacLaine" },
  { pytanie: "Rudą którego metalu jest sfaleryt?", kategoria: "Geologia/Chemia", odpowiedź: "Cynku" },
  { pytanie: "W którym mieście trasa drogi krzyżowej przebiega ulicą Via Dolorosa?", kategoria: "Geografia/Religia", odpowiedź: "W Jerozolimie" },
  { pytanie: "Jak miał na imię włoski malarz Modigliani?", kategoria: "Sztuka", odpowiedź: "Amedeo" },
  { pytanie: "Jak nazywa się chorobliwy lęk przed śmiercią?", kategoria: "Psychologia", odpowiedź: "Tanatofobia" },
  { pytanie: "Kim jest Masztalski, bohater popularnych dowcipów?", kategoria: "Obyczaje", odpowiedź: "Ślązakiem" },
  { pytanie: "Ruchów której figury nie może naśladować szachowy hetman?", kategoria: "Gry planszowe", odpowiedź: "Skoczka (konia)" },
  { pytanie: "W jakim pomieszczeniu Kazimierz Moczarski przeprowadzał swoje rozmowy z katem?", kategoria: "Historia/Literatura", odpowiedź: "W celi więziennej" },
  { pytanie: "Jak na Podhalu nazywa się właściciel gospodarstwa wiejskiego?", kategoria: "Gwara/Kultura", odpowiedź: "Gazda" },
  { pytanie: "Czyje decyzje spowodowały rozbicie dzielnicowe Polski w XII wieku?", kategoria: "Historia Polski", odpowiedź: "Bolesława Krzywoustego" },
  { pytanie: "Przedstawicielem której epoki malarstwa był francuski malarz Eugène Delacroix?", kategoria: "Sztuka", odpowiedź: "Romantyzmu" },
  { pytanie: "Jak nazywa się osoba, która zdała egzamin zawodowy, ale nie ma jeszcze nominacji (np. sędziowskiej)?", kategoria: "Prawo", odpowiedź: "Asesor" },
  { pytanie: "Czy Julian Tuwim był tłumaczem poezji?", kategoria: "Literatura", odpowiedź: "Tak (tłumaczył głównie z rosyjskiego)" },
  { pytanie: "W którym polskim mieście pierwotnie wydawany był tygodnik 'Przekrój'?", kategoria: "Kultura/Media", odpowiedź: "W Krakowie (później przeniesiony do Warszawy)" },
  { pytanie: "Proszę wymienić chociaż dwa kraje połączone unią kalmarską?", kategoria: "Historia", odpowiedź: "Dania, Szwecja, Norwegia" },
  { pytanie: "W jakim państwie panowała Katarzyna Medycejska?", kategoria: "Historia", odpowiedź: "We Francji" },
  { pytanie: "Kto był wieloletnim redaktorem naczelnym polskiej edycji Playboya (wspomniany w pytaniu)?", kategoria: "Media", odpowiedź: "Rafał Księżyk" },
  { pytanie: "W którym mieście znajduje się więzienie śledcze Łubianka?", kategoria: "Geografia/Historia", odpowiedź: "W Moskwie" },
  { pytanie: "Jak z łaciny nazywamy praktykę zawodową osób po studiach prawniczych?", kategoria: "Prawo", odpowiedź: "Aplikacja" },
  { pytanie: "W której części 'Dziadów' Adama Mickiewicza można przeczytać 'Wielką Improwizację'?", kategoria: "Literatura", odpowiedź: "W III części" },
  { pytanie: "Który półwysep Azji jest największy?", kategoria: "Geografia", odpowiedź: "Półwysep Arabski" },
  { pytanie: "Jak miał na imię Eiffel, słynny konstruktor wieży w Paryżu?", kategoria: "Historia/Architektura", odpowiedź: "Gustave (Gustaw)" },
  { pytanie: "Jak miał na imię rycerz Okrągłego Stołu pałający uczuciem do królowej Ginewry?", kategoria: "Mitologia/Literatura", odpowiedź: "Lancelot" },
  { pytanie: "Jak nazywał się pierwszy dzień każdego miesiąca w kalendarzu rzymskim?", kategoria: "Historia", odpowiedź: "Kalendy (Calendae)" },
  { pytanie: "Który władca został koronowany na króla Polski w 1025 roku po Bolesławie Chrobrym?", kategoria: "Historia Polski", odpowiedź: "Mieszko II Lambert" },
  { pytanie: "Ile figur otacza Adama Mickiewicza na jego pomniku na krakowskim Rynku?", kategoria: "Sztuka/Polska", odpowiedź: "Cztery" },
  { pytanie: "W którym wieku Karl Benz zbudował pierwszy pojazd z silnikiem spalinowym?", kategoria: "Historia/Technika", odpowiedź: "W XIX wieku (dokładnie w 1885 roku)" },
  { pytanie: "Kim dla Rembrandta była kobieta siedząca na jego kolanach na 'Autoportrecie z Saskią'?", kategoria: "Sztuka", odpowiedź: "Żoną (Saskia van Uylenburgh)" },
  { pytanie: "Jak dawniej nazywał się w Polsce atrament?", kategoria: "Język polski/Historia", odpowiedź: "Inkaust" },
  { pytanie: "Który znany utwór polskiego oświecenia Ignacego Krasickiego nosi podtytuł 'Czyli wojna mnichów'?", kategoria: "Literatura", odpowiedź: "Monachomachia" },
  { pytanie: "Jak nazywa się jedno z siedmiu wzgórz Rzymu, na którym znajduje się Pałac Kwirynalski (siedziba prezydenta, dawniej premiera)?", kategoria: "Geografia/Polityka", odpowiedź: "Kwirynał" },
  { pytanie: "Mincerz to pracownik mennicy czy kopalni węgla?", kategoria: "Historia/Gospodarka", odpowiedź: "Mennicy" },
  { pytanie: "Ile rzek w Polsce ma długość większą niż 1000 km?", kategoria: "Geografia Polski", odpowiedź: "Jedna (Wisła)" },
  { pytanie: "Jak nazywa się polski okręt bojowy z II WŚ, który jako okręt-muzeum cumuje w Gdyni?", kategoria: "Militaria/Polska", odpowiedź: "ORP Błyskawica" },
  { pytanie: "Ile to jest cztery podniesione do sześcianu (4 do potęgi 3)?", kategoria: "Matematyka", odpowiedź: "64" }, // Poprawiłem z 256 (256 to 4 do potęgi 4)
  { pytanie: "Jak nazywał się dziewiętnastowieczny norweski kompozytor, który skomponował suitę 'Peer Gynt' (z utworem 'W grocie króla gór')?", kategoria: "Muzyka", odpowiedź: "Edvard Grieg" },
  { pytanie: "W jakim języku wydane było dzieło medyczne Wojciecha Oczki 'Cieplice' (Leczenie balneologiczne) z XVI wieku?", kategoria: "Literatura/Medycyna", odpowiedź: "Po polsku" },
  { pytanie: "Którego ucha brakuje Vincentowi van Goghowi na obrazie 'Autoportret z zabandażowanym uchem'?", kategoria: "Sztuka", odpowiedź: "Prawego (choć w rzeczywistości odciął sobie lewe – malował odbicie w lustrze)" },
  { pytanie: "Jak nazywa się największe zwierzę z rodziny fokowatych?", kategoria: "Przyroda", odpowiedź: "Słoń morski" },
  { pytanie: "Jaką dyscyplinę uprawia Patrick Chan, wielokrotny mistrz świata?", kategoria: "Sport", odpowiedź: "Łyżwiarstwo figurowe" },
  { pytanie: "Który utwór Zbigniewa Herberta kończy się słowami 'Bądź wierny Idź'?", kategoria: "Literatura", odpowiedź: "Przesłanie Pana Cogito" },
  { pytanie: "Kto jest głównym patronem arcybazyliki na Lateranie w Rzymie?", kategoria: "Religia", odpowiedź: "Św. Jan (Chrzciciel i Ewangelista)" },
  { pytanie: "Jak nazywa się fachowiec zajmujący się analizą pisma ręcznego?", kategoria: "Nauka", odpowiedź: "Grafolog" },
  { pytanie: "Co dosłownie po łacinie oznacza zwrot 'vademecum'?", kategoria: "Język łaciński", odpowiedź: "Pójdź za mną" },
  { pytanie: "W jakim polskim filmie (ekranizacji powieści) Jerzy Bińczycki jako Toliboski zrywa nenufary (lilie wodne) ze stawu?", kategoria: "Film", odpowiedź: "Noce i dnie" },
  { pytanie: "Czy w dziele 'O skutecznym rad sposobie' Stanisław Konarski zalecał zniesienie liberum veto?", kategoria: "Historia Polski/Literatura", odpowiedź: "Tak" },
  { pytanie: "Co ile lat przyznawane są amerykańskie Nagrody Pulitzera?", kategoria: "Inne", odpowiedź: "Co roku" },
  { pytanie: "Szlif kaboszonowy w jubilerstwie to szlif wypukły czy wklęsły?", kategoria: "Inne", odpowiedź: "Szlif wypukły (gładki, bez faset)" },
  { pytanie: "Jak nazywa się zewnętrzna, pofałdowana warstwa półkul mózgowych?", kategoria: "Medycyna/Anatomia", odpowiedź: "Kora mózgowa" },
  { pytanie: "Jak nazywała się jedyna kobieta, która pełniła funkcję premiera Izraela?", kategoria: "Historia", odpowiedź: "Golda Meir" },
  { pytanie: "W którym wieku zostało zbudowane słynne wiedeńskie diabelskie koło (Riesenrad)?", kategoria: "Historia/Inne", odpowiedź: "W XIX wieku (1897 r.)" },
  { pytanie: "Jak nazywał się jacht, na którym Leonid Teliga jako pierwszy Polak samotnie opłynął świat?", kategoria: "Sport/Historia", odpowiedź: "Opty" },
  { pytanie: "Jak z francuskiego określamy okulary trzymające się na nosie za pomocą sprężyny, bez zauszników?", kategoria: "Inne", odpowiedź: "Binokle" },
  { pytanie: "Gdzie (w jakim państwie) powstała pierwsza na świecie regularna rozgłośnia radiowa?", kategoria: "Historia/Media", odpowiedź: "W USA (KDKA w Pittsburghu, 1920 r.)" },
  { pytanie: "Jak brzmiało przezwisko zbójnika, kompana Janosika, którego w serialu zagrał Witold Pyrkosz?", kategoria: "Film", odpowiedź: "Pyzdra" },
  { pytanie: "W którym wieku wybrany został pierwszy w historii papież spoza Europy (Franciszek)?", kategoria: "Historia/Religia", odpowiedź: "W XXI wieku (2013 r.)" },
  { pytanie: "Ile razy w swoje wielkie wyprawy badawcze dookoła świata wyruszał James Cook?", kategoria: "Historia/Odkrycia", odpowiedź: "Trzy razy" },
  { pytanie: "Która okrągła rocznica powstania w getcie warszawskim minęła w 2013 roku?", kategoria: "Historia Polski", odpowiedź: "70. rocznica" }, // Skorygowałem z 60. (1943 -> 2013 to 70 lat)
  { pytanie: "Którym z kolei królem elekcyjnym na polskim tronie był Stefan Batory?", kategoria: "Historia Polski", odpowiedź: "Drugim" },
  { pytanie: "W pobliżu jakiego jeziora rozgrywa się akcja dramatu 'Balladyna' Juliusza Słowackiego?", kategoria: "Literatura", odpowiedź: "Gopło" },
  { pytanie: "Weredyk to osoba mówiąca bezkompromisowo prawdę czy kłamca?", kategoria: "Język polski", odpowiedź: "Mówiąca prawdę" },
  { pytanie: "Na terenie jakiego państwa leży Puszcza Knyszyńska?", kategoria: "Geografia", odpowiedź: "Na terenie Polski" },
  { pytanie: "Która rzeka przepływa przez Bydgoszcz i tam wpada do Wisły?", kategoria: "Geografia Polski", odpowiedź: "Brda" }, // Zmieniłem z Gwda, bo Gwda uchodzi do Noteci w Pile
  { pytanie: "Z jakiego kraju pochodzi słynny pieśniarz i kompozytor Jaromír Nohavica?", kategoria: "Muzyka", odpowiedź: "Z Czech" },
  { pytanie: "Jak miała na imię według legend arturiańskich żona króla Artura, ukochana Lancelota?", kategoria: "Mitologia/Literatura", odpowiedź: "Ginewra" },
  { pytanie: "Wysoki Komisarz Narodów Zjednoczonych do spraw Uchodźców (UNHCR) to agenda UE czy ONZ?", kategoria: "Polityka", odpowiedź: "ONZ" },
  { pytanie: "Kto w XIX wieku wynalazł szczepionkę przeciwko wściekliźnie?", kategoria: "Nauka/Medycyna", odpowiedź: "Ludwik Pasteur" },
  { pytanie: "Jak nazywa się stała matematyczna określająca stosunek długości obwodu okręgu do jego średnicy?", kategoria: "Matematyka", odpowiedź: "Pi" },
  { pytanie: "W którym roku zmarł wybitny malarz Pablo Picasso?", kategoria: "Sztuka", odpowiedź: "W 1973 roku" },
  { pytanie: "W którym polskim powstaniu narodowym rozegrała się zwycięska bitwa pod Stoczkiem?", kategoria: "Historia Polski", odpowiedź: "W powstaniu listopadowym" },
  { pytanie: "Jak nazywa się silny narkotyk opioidowy, którego nazwa pochodzi od greckiego boga snu?", kategoria: "Medycyna", odpowiedź: "Heroina" },
  { pytanie: "Jak miał na imię pisarz i polityk oświeceniowy Niemcewicz, autor 'Powrotu posła'?", kategoria: "Literatura/Historia", odpowiedź: "Julian Ursyn" },
  { pytanie: "W którym roku odbyła się słynna morska bitwa pod Trafalgarem?", kategoria: "Historia", odpowiedź: "1805" },
  { pytanie: "Który gaz charakteryzuje się najlepszym przewodnictwem cieplnym?", kategoria: "Fizyka/Chemia", odpowiedź: "Wodór" },
  { pytanie: "Jak nazywa się uruchomiony w Chile w 2013 roku największy na świecie naziemny interferometr radioteleskopów?", kategoria: "Astronomia/Technika", odpowiedź: "ALMA" },
  { pytanie: "Ilu powstańców widać na znanym obrazie Aleksandra Gierymskiego 'Patrol powstańczy'?", kategoria: "Sztuka/Historia Polski", odpowiedź: "Czterech" },
  { pytanie: "Jak nazywa się wirus wywołujący groźną chorobę Heinego-Medina?", kategoria: "Medycyna", odpowiedź: "Wirus polio" },
  { pytanie: "W jakich górach azjatyckich znajduje się ośmiotysięcznik Broad Peak?", kategoria: "Geografia", odpowiedź: "Karakorum" },
  { pytanie: "Jak nazywa się potocznie węglik wapnia, służący m.in. do produkcji acetylenu?", kategoria: "Chemia", odpowiedź: "Karbid" },
  { pytanie: "Jakie ciężkie przestępstwo popełniła Małgorzata, bohaterka 'Fausta' Goethego, pod wpływem rozpaczy?", kategoria: "Literatura", odpowiedź: "Dzieciobójstwo (zabiła swoje nieślubne dziecko)" },
  { pytanie: "W jakim państwie spędził ostatnie lata życia i zmarł Leonardo da Vinci?", kategoria: "Historia/Sztuka", odpowiedź: "We Francji" },
  { pytanie: "Jakie zwierzęta według legendy ocaliły Rzym przed najazdem Galów w IV w. p.n.e.?", kategoria: "Historia/Mitologia", odpowiedź: "Gęsi kapitolińskie" },
  { pytanie: "W którym wieku żył i tworzył słynny filozof Baruch Spinoza?", kategoria: "Filozofia/Historia", odpowiedź: "W XVII wieku" },
  { pytanie: "Tytułu którego dramatu Szekspira według przesądu teatralnego nie wolno wymawiać na głos w teatrze?", kategoria: "Teatr/Literatura", odpowiedź: "Makbeta" },
  { pytanie: "Czy włosko-amerykański fizyk Enrico Fermi, twórca pierwszego reaktora jądrowego, był laureatem Nagrody Nobla?", kategoria: "Fizyka/Nauka", odpowiedź: "Tak" },
  { pytanie: "Jak nazywał się żyjący w IV wieku teolog, twórca arianizmu negującego Trójcę Świętą?", kategoria: "Historia/Religia", odpowiedź: "Ariusz" },
  { pytanie: "Ile łącznie dzieci (synów i córek) straciła według mitu Niobe na skutek gniewu Apollina i Artemidy?", kategoria: "Mitologia", odpowiedź: "14 (7 synów i 7 córek)" },
  { pytanie: "Jak z języka niemieckiego nazywamy w żeglarstwie płynięcie zakosami pod wiatr?", kategoria: "Sport", odpowiedź: "Halsowanie" },
  { pytanie: "Jak nazywa się rząd ssaków łożyskowych, do którego tradycyjnie zaliczano mrówkojady, leniwce i pancerniki?", kategoria: "Przyroda", odpowiedź: "Szczerbaki" },
  { pytanie: "Ile łącznie mazurków na fortepian skomponował w ciągu swojego życia Fryderyk Chopin?", kategoria: "Muzyka", odpowiedź: "57" },
  { pytanie: "W jakim europejskim kraju przyznawany jest najwyższy order zasługi zwany Orderem Słonia?", kategoria: "Świat/Obyczaje", odpowiedź: "W Danii" },
  { pytanie: "Kto pełnił funkcję marszałka Sejmu Czteroletniego w chwili uroczystego uchwalenia Konstytucji 3 Maja?", kategoria: "Historia Polski", odpowiedź: "Stanisław Małachowski" },
  { pytanie: "W którym wieku ostatecznie ukończono budowę słynnego kamiennego Mostu Karola na Wełtawie w Pradze?", kategoria: "Historia/Architektura", odpowiedź: "W XIV wieku (rozpoczęto w 1357 r. za panowania Karola IV)" },
  { pytanie: "W których strukturach ludzkiego organizmu zachodzi proces powstawania erytrocytów?", kategoria: "Medycyna/Anatomia", odpowiedź: "W szpiku kostnym (czerwonym)" },
  { pytanie: "Jak nazywał się wybitny polski malarz historyczny, autor obrazu 'Nocne przygody Jana Olbrachta'?", kategoria: "Sztuka", odpowiedź: "Jan Matejko" },
  { pytanie: "W 2013 roku zrekonstruowano cyfrowo pierwszy krótkometrażowy film pokazujący przedwojenną Warszawę z lotu ptaka. Z którego roku pochodziły ujęcia?", kategoria: "Historia Polski/Film", odpowiedź: "Z 1935 roku ('Warszawa 1935')" },
  { pytanie: "W jakiej słynnej renesansowej książce Niccolò Machiavelli zawarł myśli sprowadzające się do zasady 'cel uświęca środki'?", kategoria: "Literatura/Filozofia", odpowiedź: "'Książę'" },
  { pytanie: "Nad jaką wielką zatoką geograficzną leży stolica Kuby, Hawana?", kategoria: "Geografia", odpowiedź: "Nad Zatoką Meksykańską" },
  { pytanie: "Czyje burzliwe życie i karierę opisuje autobiograficzna książka pt. 'Moonwalk'?", kategoria: "Muzyka", odpowiedź: "Michaela Jacksona" },
  { pytanie: "Jaka wielka, krwawa i taktycznie nierozstrzygnięta bitwa z czasów napoleońskich została szczegółowo opisana w powieści 'Wojna i pokój' Lwa Tołstoja?", kategoria: "Literatura", odpowiedź: "Bitwa pod Borodino" },
  { pytanie: "Jakie nowe, symboliczne imię nadał Bóg biblijnemu Jakubowi po jego nocnej walce z aniołem?", kategoria: "Religia", odpowiedź: "Izrael" },
  { pytanie: "Liderem którego legendarnego brytyjskiego zespołu heavymetalowego był przez lata wokalista Ozzy Osbourne?", kategoria: "Muzyka", odpowiedź: "Black Sabbath" },
  { pytanie: "Tradycyjną potrawą mączną (rodzajem chlebka lub placka) z którego kraju jest maslenica?", kategoria: "Kulinaria", odpowiedź: "Z Rosji" },
  { pytanie: "Który wybitny polski generał dowodził bohaterską Armią 'Poznań' podczas kampanii wrześniowej i bitwy nad Bzurą?", kategoria: "Historia Polski", odpowiedź: "gen. Tadeusz Kutrzeba" },
  { pytanie: "Czyim synem i bezpośrednim następcą w dążeniach do odbudowy państwa był książę Kazimierz I Odnowiciel?", kategoria: "Historia Polski", odpowiedź: "Mieszka II Lamberta" },
  { pytanie: "Ilu oficjalnie wybranych prezydentów pełniło urząd w Polsce w okresie międzywojennym (II RP)?", kategoria: "Historia Polski", odpowiedź: "Trzech (Gabriel Narutowicz, Stanisław Wojciechowski, Ignacy Mościcki)" },
  { pytanie: "Jak miał na imię dr Chałubiński, zasłużony lekarz, taternik i wielki propagator klimatycznych walorów Zakopanego?", kategoria: "Historia Polski", odpowiedź: "Tytus" },
  { pytanie: "Radogoszcz (Radogost), Strzybóg oraz Perun to potężne bóstwa czczone pierwotnie w której mitologii?", kategoria: "Religia/Mitologia", odpowiedź: "W mitologii słowiańskiej" },
  { pytanie: "Aktorka Emmanuelle Seigner jest prywatnie żoną którego słynnego polsko-francuskiego reżysera filmowego?", kategoria: "Film", odpowiedź: "Romana Polańskiego" },
  { pytanie: "Jak nazywała się genialna brytyjska pisarka, autorka kryminałów i twórczyni legendarnej postaci detektywa Herkulesa Poirota?", kategoria: "Literatura", odpowiedź: "Agatha Christie" },
  { pytanie: "Wojna trzynastoletnia z Zakonem Krzyżackim rozpoczęła się historycznie przed czy po słynnej bitwie pod Grunwaldem?", kategoria: "Historia Polski", odpowiedź: "Po (Grunwald to 1410 r., wojna trzynastoletnia to lata 1454–1466)" },
  { pytanie: "Jak należy pisać słowo 'Europarlament' w świetle zasad polskiej ortografii, gdy mamy na myśli instytucję unijną jako nazwę własną?", kategoria: "Ortografia", odpowiedź: "Wielką literą" },
  { pytanie: "Słynna i uwielbiana przez tłumy Maria Eva Duarte de Perón (znana jako Evita) była żoną którego prezydenta Argentyny?", kategoria: "Historia", odpowiedź: "Juana Peróna" },
  { pytanie: "Ile niezależnych izb ustawodawczych liczy współczesny parlament w Indiach (Sansad)?", kategoria: "Polityka/Świat", odpowiedź: "Dwie (Izba Ludowa – Lok Sabha oraz Izba Stanów – Rajya Sabha)" },
  { pytanie: "Który geograficzny punkt topograficzny jest wyższy: polski Giewont czy najwyższy szczyt Australii – Góra Kościuszki?", kategoria: "Geografia", odpowiedź: "Góra Kościuszki (2228 m n.p.m. vs Giewont 1894 m n.p.m.)" },
  { pytanie: "Imieniem którego wybitnego polskiego pisarza i nowelisty została uroczyście nazwana latarnia morska na Przylądku Rozewie?", kategoria: "Literatura/Polska", odpowiedź: "Stefana Żeromskiego" },
  { pytanie: "Czy tradycyjny język jidysz jest obecnie oficjalnym urzędowym językiem w państwie Izrael?", kategoria: "Językoznawstwo", odpowiedź: "Nie (urzędowym jest hebrajski, dawniej status ten miał też arabski)" },
  { pytanie: "Słynny grecki dziejopis Herodot w swoim pomnikowym dziele 'Dzieje' opisał głównie wielkie podboje Aleksandra Macedońskiego. Prawda czy fałsz?", kategoria: "Historia", odpowiedź: "Fałsz (opisał wojny perskie; żył przed Aleksandrem Wielkim)" },
  { pytanie: "Jak w grze w brydża nazywamy kontrakt zapowiadający zobowiązanie do wzięcia dokładnie dwunastu lew?", kategoria: "Gry planszowe/Karciane", odpowiedź: "Małym szlemem" },
  { pytanie: "Wielka azjatycka rzeka Eufrat przepływa przez terytoria trzech państw. Proszę wymienić przynajmniej dwa z nich.", kategoria: "Geografia", odpowiedź: "Turcja, Syria, Irak" },
  { pytanie: "Z ilu głównych, chronologicznych części składają się staropolskie 'Pamiętniki' Jana Chryzostoma Paska?", kategoria: "Literatura", odpowiedź: "Z dwóch części" },
  { pytanie: "Który wybitny XVII-wieczny toskański uczony sformułował prawo ruchu izochronicznego wahadła?", kategoria: "Fizyka/Historia", odpowiedź: "Galileusz" },
  { pytanie: "Na którym kontynencie (w środkowo-wschodniej części) żyją afrykańskie ludy Hutu i Tutsi?", kategoria: "Geografia/Socjologia", odpowiedź: "W Afryce" },
  { pytanie: "Tradycyjny szeroki pas tkaniny owijany wokół stóp, zwany onucą, z którego ostatecznie wycofała się armia rosyjska, zastępował żołnierzom koszulę czy skarpety?", kategoria: "Militaria/Historia", odpowiedź: "Skarpety" },
  { pytanie: "Król Władysław II Jagiełło był żonaty czterokrotnie. Proszę wymienić imiona przynajmniej dwóch z jego małżonek.", kategoria: "Historia Polski", odpowiedź: "Jadwiga (Andegaweńska), Anna (Cylejska), Elżbieta (Granowska), Zofia (Holszańska)" },
  { pytanie: "Jak nazywa się mityczny skrzydlaty koń, który zrodził się z krwi Meduzy i stał się symbolem natchnienia poetów?", kategoria: "Mitologia/Literatura", odpowiedź: "Pegaz" },
  { pytanie: "Który genialny barokowy kompozytor, pełniący funkcję kantora przy kościele św. Tomasza w Lipsku, stworzył zbiór 6 Koncertów Brandenburskich?", kategoria: "Muzyka", odpowiedź: "Jan Sebastian Bach" },
  { pytanie: "Ile razy według tradycji chrześcijańskiej i stacji nabożeństwa Jezus Chrystus upadł pod ciężarem krzyża?", kategoria: "Religia", odpowiedź: "Trzy razy" },
  { pytanie: "Jak nazywa się dziennikarka, wieloletnia autorka i prowadząca interwencyjny program publicystyczny 'Sprawa dla reportera'?", kategoria: "Telewizja/Polska", odpowiedź: "Elżbieta Jaworowicz" },
  { pytanie: "Kto stał na czele największego i najkrwawszego w starożytnym Rzymie powstania niewolników w latach 73–71 p.n.e.?", kategoria: "Historia", odpowiedź: "Spartakus" },
  { pytanie: "W którym amerykańskim mieście uroczyście zredagowano i podpisano w 1776 roku historyczną Deklarację Niepodległości Stanów do USA?", kategoria: "Historia", odpowiedź: "W Filadelfii" },
  { pytanie: "Promil jako jednostka matematyczna – jaka to dokładnie część jednej całości?", kategoria: "Matematyka", odpowiedź: "Tysięczna ($1/1000$)" },
  { pytanie: "Z hiszpańskiego, co dosłownie oznacza nazwa popularnej i skocznej pieśni ludowej 'La Cucaracha'?", kategoria: "Język hiszpański/Muzyka", odpowiedź: "Karaluch" },
  { pytanie: "Pod jaką specyficzną i niezwykłą postacią mitologiczny Zeus uwiódł piękną Danae, uwięzioną przez ojca w miedzianej wieży?", kategoria: "Mitologia", odpowiedź: "Pod postacią złotego deszczu" },
  { pytanie: "Głównym zadaniem globalnej instytucji kulturalnej o nazwie Instytut Goethego (Goethe-Institut) jest popularyzacja kultury oraz którego języka?", kategoria: "Kultura/Języki", odpowiedź: "Niemieckiego" },
  { pytanie: "Czy naturalna, czysta kasza kukurydziana zawiera w swoim składzie białkowym gluten?", kategoria: "Kulinaria/Medycyna", odpowiedź: "Nie (kukurydza jest zbożem naturalnie bezglutenowym)" },
  { pytanie: "Prorogacja budżetu państwowego w prawie finansowym oznacza skrócenie czy też ustawowe przedłużenie mocy obowiązującej dotychczasowego budżetu?", kategoria: "Prawo/Ekonomia", odpowiedź: "Przedłużenie" },
  { pytanie: "Który wybitny polski kompozytor awangardowy stworzył w 1960 roku poruszający utwór orkiestrowy zatytułowany 'Tren ofiarom Hiroszimy'?", kategoria: "Muzyka", odpowiedź: "Krzysztof Penderecki" },
  { pytanie: "Który znany amerykański prezydent reprezentował USA podczas kluczowej konferencji wielkiej trójki w Jałcie w 1945 roku?", kategoria: "Historia", odpowiedź: "Franklin Delano Roosevelt" },
  { pytanie: "Czy wybitny grecki matematyk, fizyk i wynalazca Archimedes żył przed czy po Chrystusie?", kategoria: "Historia", odpowiedź: "Przed Chrystusem" },
  { pytanie: "Jaki oficjalny tytuł nosiła brytyjska królowa Wiktoria jako władczyni imperium kolonialnego w Indiach?", kategoria: "Historia", odpowiedź: "Cesarzowa Indii" },
  { pytanie: "Według wiersza Jana Brzechwy, w którym mieście rośnie trzcina, w której 'chrabąszcz brzmi'?", kategoria: "Literatura", odpowiedź: "W Szczebrzeszynie" },
  { pytanie: "Zupa Bouillabaisse (bujabes), przyrządzana z wielu gatunków ryb i owoców morza, to przysmak kuchni którego państwa?", kategoria: "Kulinaria", odpowiedź: "Francji" },
  { pytanie: "W którym miesiącu w Poznaniu w 1956 roku miał miejsce pierwszy w PRL masowy protest robotniczy?", kategoria: "Historia Polski", odpowiedź: "W czerwcu (Poznański Czerwiec)" },
  { pytanie: "Który z legendarnych angielskich uniwersytetów jest starszy chronologicznie: Cambridge czy Oxford?", kategoria: "Historia", odpowiedź: "Oxford" },
  { pytanie: "Jakie imię nosi archanioł opisany w biblijnej Księdze Daniela jako anioł-opiekun narodu izraelskiego?", kategoria: "Religia", odpowiedź: "Michał" },
  { pytanie: "Na terenie którego współczesnego państwa leżą miasta Jaipur (Dżajpur), Raipur (Rajpur) oraz Madras?", kategoria: "Geografia", odpowiedź: "W Indiach" },
  { pytanie: "Ile centymetrów sześciennych ($cm^3$) mieści się dokładnie w jednym metrze sześciennym ($m^3$)?", kategoria: "Matematyka", odpowiedź: "Milion ($1\\ 000\\ 000$)" },
  { pytanie: "Kto jest słynnym pomysłodawcą i wieloletnim prowadzącym Listę Przebojów Programu Trzeciego Polskiego Radia?", kategoria: "Muzyka/Media", odpowiedź: "Marek Niedźwiecki" },
  { pytanie: "Dokąd udała się tytułowa Karolinka w popularnej śląskiej pieśni ludowej?", kategoria: "Kultura/Muzyka", odpowiedź: "Do Gogolina" },
  { pytanie: "Jak w XII i XIII wieku w Polsce nazywał się urzędnik królewski sprawujący władzę nad grodem lub zamkiem i przyległym okręgiem?", kategoria: "Historia Polski", odpowiedź: "Kasztelan" },
  { pytanie: "Która słynna francuska aktorka w 1975 roku zrezygnowała z kariery filmowej, by założyć fundację ochrony zagrożonych zwierząt?", kategoria: "Film/Świat", odpowiedź: "Brigitte Bardot" },
  { pytanie: "Z którego miasta pochodzi i w swojej twórczości folku miejskiego się specjalizuje Kapela Czerniakowska?", kategoria: "Muzyka/Polska", odpowiedź: "Z Warszawy" },
  { pytanie: "Ile łącznie złotych medali zdobyli reprezentanci Polski na zimowych igrzyskach olimpijskich do tej pory?", kategoria: "Sport", odpowiedź: "7 (Wojciech Fortuna, Justyna Kowalczyk x2, Kamil Stoch x3, Zbigniew Bródka)" },
  { pytanie: "Który polski król dowodził zjednoczonymi wojskami i spektakularnie pokonał Turków pod Wiedniem w 1683 roku?", kategoria: "Historia Polski", odpowiedź: "Jan III Sobieski" },
  { pytanie: "Czy Marcus Winicjusz, jeden z głównych bohaterów powieści 'Quo Vadis' Henryka Sienkiewicza, został ostatecznie chrześcijaninem?", kategoria: "Literatura", odpowiedź: "Tak" },
  { pytanie: "Jak z łaciny nazywa się powszechne medyczne schorzenie zmętnienia soczewki oka, zwane po polsku zaćmą?", kategoria: "Medycyna", odpowiedź: "Katarakta" },
  { pytanie: "Mahatma (Wielka Dusza) to honorowy tytuł nadawany wybitnym przywódcom duchowym i społecznym w którym państwie?", kategoria: "Świat/Religia", odpowiedź: "W Indiach" },
  { pytanie: "Która starożytna armia wyszła ostatecznie zwycięsko z I wojny punickiej?", kategoria: "Historia", odpowiedź: "Rzymska" },
  { pytanie: "W którym kultowym polskim filmie Marka Piwowskiego Zdzisław Maklakiewicz przedstawia się słowami: 'Inżynier Mamoń jestem'?", kategoria: "Film", odpowiedź: "Rejs" },
  { pytanie: "Kto założył w Indiach katolickie Zgromadzenie Sióstr Misjonarek Miłości?", kategoria: "Religia", odpowiedź: "Matka Teresa z Kalkuty" },
  { pytanie: "Nad jakim elementem natury sprawował mitologiczną władzę grecki bóg Eol?", kategoria: "Mitologia", odpowiedź: "Nad wiatrami" },
  { pytanie: "Czy w tradycyjny skład chóru/zespołu rewelersów wchodzą kobiety?", kategoria: "Muzyka", odpowiedź: "Nie (jest to wyłącznie męski kwartet wokalny)" },
  { pytanie: "Podczas którego polskiego powstania narodowego w XVIII wieku formacje kosynierów po raz pierwszy wspomogły armię regularną?", kategoria: "Historia Polski", odpowiedź: "Podczas insurekcji kościuszkowskiej" },
  { pytanie: "Co po polsku oznacza dosłownie powszechnie używany łaciński zwrot 'mea culpa'?", kategoria: "Język łaciński", odpowiedź: "Moja wina" },
  { pytanie: "Czy biblijni Dawid i Goliat, którzy zmierzyli się w słynnym pojedynku, byli ze sobą spokrewnieni jako bracia?", kategoria: "Religia", odpowiedź: "Nie" },
  { pytanie: "Kto historycznie uchodzi za oficjalnego, pierwszego konstruktora działającego perpetuum mobile?", kategoria: "Nauka/Historia", odpowiedź: "Nikt (zgodnie z prawami termodynamiki jego zbudowanie jest niemożliwe)" },
  { pytanie: "Osobę zachowującą się nietaktownie, niezgrabnie lub potykającą się w delikatnej sytuacji porównuje się w przysłowiu do jakiego zwierzęcia w składzie porcelany?", kategoria: "Przysłowia", odpowiedź: "Do słonia (słoń w składzie porcelany)" },
  { pytanie: "Który polski król był oficjalnym gospodarzem słynnej średniowiecznej uczty monarchów wydanej w Krakowie przez Mikołaja Wierzynka?", kategoria: "Historia Polski", odpowiedź: "Kazimierz III Wielki" },
  { pytanie: "Czy staropolskie żarna to dawne urządzenia mechaniczne do mielenia ziwna na mąkę, czy pojemnik na żar z paleniska?", kategoria: "Historia/Technika", odpowiedź: "Urządzenie do mielenia ziarna" },
  { pytanie: "W którym holenderskim mieście można zwiedzać słynne Muzeum van Gogha oraz zabytkowy Dom Rembrandta?", kategoria: "Geografia/Sztuka", odpowiedź: "W Amsterdamie" },
  { pytanie: "W którym państwie najwyższym i najbardziej prestiżowym odznaczeniem wojennym za męstwo jest Krzyż Wiktorii (Victoria Cross)?", kategoria: "Militaria/Świat", odpowiedź: "W Wielkiej Brytanii" },
  { pytanie: "Jakie nazwisko (późniejszy przydomek rodowy) nosił tytułowy bohater poematu 'Pan Tadeusz' Adama Mickiewicza?", kategoria: "Literatura", odpowiedź: "Soplica" },
  { pytanie: "Kraina historyczno-geograficzna Prowansja, znana m.in. z pól lawendy, leży w południowej czy północnej części Francji?", kategoria: "Geografia", odpowiedź: "W południowej" },
  { pytanie: "W którym warszawskim parku stoi dawny budynek Szkoły Podchorążych, skąd spiskowcy ruszyli do nocy listopadowej?", kategoria: "Historia Polski/Geografia", odpowiedź: "W Łazienkach Królewskich" },
  { pytanie: "Kto jest autorem klasycznej przygodowej powieści XIX-wiecznej 'Dzieci kapitana Granta'?", kategoria: "Literatura", odpowiedź: "Juliusz Verne" },
  { pytanie: "Co dokładnie ma pod stopami rzymska bogini miłości na słynnym renesansowym obrazie Sandro Botticellego 'Narodziny Wenus'?", kategoria: "Sztuka", odpowiedź: "Wielką muszlę" },
  { pytanie: "W jakim języku w oryginale została w całości napisana i przetłumaczona przez św. Hieronima Biblia zwana Wulgatą?", kategoria: "Religia/Języki", odpowiedź: "W łacinie" },
  { pytanie: "Tę samą nazwę nosi wojskowy pocisk miotany ręką, czerwony kamień półszlachetny oraz owoc południowy. Jaka to nazwa?", kategoria: "Inne", odpowiedź: "Granat" },
  { pytanie: "W którym europejskim państwie leży historyczna i owiana legendami kraina geograficzna zwana Transsylwanią (Siedmiogrodem)?", kategoria: "Geografia", odpowiedź: "W Rumunii" },
  { pytanie: "Kogo wyznawcy islamu w kontekście historycznym i literackim określali mianem 'giaurów'?", kategoria: "Religia/Literatura", odpowiedź: "Innowierców (najczęściej chrześcijan)" },
  { pytanie: "Jakiej narodowości był humanista i pisarz Filip Kallimach, który był nauczycielem synów króla Kazimierza Jagiellończyka?", kategoria: "Historia Polski", odpowiedź: "Włochem (urodził się w Toskanii)" },
  { pytanie: "Od imienia której starożytnej postaci historycznej bezpośrednio wywodzi się monarszy tytuł władcy – 'cesarz'?", kategoria: "Historia", odpowiedź: "Od Juliusza Cezara" },
  { pytanie: "Na której greckiej wyspie na Morzu Egejskim stał potężny Kolos – posąg boga Heliosa zaliczany do siedmiu cudów świata?", kategoria: "Historia/Mitologia", odpowiedź: "Na Rodos" },
  { pytanie: "Młody Cezary Baryka to główny bohater której wybitnej powieści polityczno-społecznej Stefana Żeromskiego?", kategoria: "Literatura", odpowiedź: "Przedwiośnie" },
  { pytanie: "Na którym paryskim wzgórzu wznosi się słynna biała bazylika Sacré-Cœur?", kategoria: "Geografia", odpowiedź: "Montmartre" },
  { pytanie: "W którym europejskim państwie w XV wieku toczyła się krwawa wojna domowa o sukcesję tronu, zwana 'Wojną Dwóch Róż'?", kategoria: "Historia", odpowiedź: "W Anglii" },
  { pytanie: "Z której dynastii królewskiej pochodził król Zygmunt III, który podjął decyzję o przeniesieniu stałego dworu i stolicy z Krakowa do Warszawy?", kategoria: "Historia Polski", odpowiedź: "Z dynastii Wazów" },
  { pytanie: "Jakim terminem naukowym pochodzącym z greki określamy w archeologii najwcześniejszą epokę kamienia, zwaną łupanym?", kategoria: "Historia/Archeologia", odpowiedź: "Paleolit" },
  { pytanie: "Jak z greki medycznie nazywa się przewlekła dychawica oskrzelowa?", kategoria: "Medycyna", odpowiedź: "Astma" },
  { pytanie: "Aaron, pierwszy biblijny arcykapłan, był starszym bratem którego wielkiego proroka?", kategoria: "Religia", odpowiedź: "Mojżesza" },
  { pytanie: "Co w środowisku wspinaczkowym i alpinistycznym oznacza prestiżowe pojęcie 'Korona Ziemi'?", kategoria: "Sport", odpowiedź: "Najwyższe szczyty poszczególnych kontynentów" },
  { pytanie: "Za zdjęcia do którego filmu Stevena Spielberga polski operator Janusz Kamiński otrzymał nominację do Oscara w 2013 roku?", kategoria: "Film", odpowiedź: "Do filmu 'Lincoln'" },
  { pytanie: "Kto dowodził zwycięskimi wojskami polskimi w 1673 roku w drugiej bitwie pod Chocimiem?", kategoria: "Historia Polski", odpowiedź: "Jan III Sobieski (wówczas hetman wielki koronny)" },
  { pytanie: "Zabytek piśmiennictwa 'Psałterz floriański' z przełomu XIV i XV wieku tradycyjnie wiąże się z imieniem której królowej Polski?", kategoria: "Historia Polski/Literatura", odpowiedź: "Świętej Jadwigi Andegaweńskiej" },
  { pytanie: "Proszę wymienić przynajmniej jedną z tak zwanych czterech rzeczy ostatecznych człowieka w chrześcijańskiej teologii dogmatycznej.", kategoria: "Religia", odpowiedź: "Śmierć, sąd, niebo lub piekło" },
  { pytanie: "Ile galaktyk satelitarnych Drogi Mlecznej nosi w swojej oficjalnej nazwie nazwisko podróżnika Magellana?", kategoria: "Astronomia", odpowiedź: "Dwie (Wielki i Mały Obłok Magellana)" },
  { pytanie: "W którym okresie historyczno-kulturalnym działali w Polsce tacy reformatorzy jak Hugo Kołłątaj czy Stanisław Konarski?", kategoria: "Historia Polski", odpowiedź: "W oświeceniu" },
  { pytanie: "W którym włoskim mieście znajduje się słynna Krzywa Wieża, będąca w rzeczywistości dzwonnicą tamtejszej katedry?", kategoria: "Geografia/Architektura", odpowiedź: "W Pizie" },
  { pytanie: "W pierwszej połowie którego wieku na scenach europejskich triumfy święcił balet Siergieja Diagilewa pod nazwą 'Balety Rosyjskie'?", kategoria: "Sztuka/Historia", odpowiedź: "W XX wieku" },
  { pytanie: "Która legendarna aktorka zagrała niezapomniane główne role w przedwojennych filmach 'Błękitny anioł' oraz 'Blond Wenus'?", kategoria: "Film", odpowiedź: "Marlene Dietrich" },
  { pytanie: "Francuski badacz Albert Calmette wraz z Camille'em Guérinem opracował w XX wieku przełomową szczepionkę BCG przeciwko jakiej chorobie?", kategoria: "Medycyna/Historia", odpowiedź: "Przeciwko gruźlicy" },
  { pytanie: "Który z dwóch amerykańskich prezydentów z rodziny Bushów sprawował swój urząd dłużej (przez dwie kadencje): senior czy junior?", kategoria: "Historia/Świat", odpowiedź: "Junior (George W. Bush)" },
  { pytanie: "Na których fantastycznych wyspach, według satyrycznego wiersza Jana Brzechwy, 'widziano osła, którego mrówka niosła'?", kategoria: "Literatura", odpowiedź: "Na wyspach Bergamutach" },
  { pytanie: "Jakie ręczne, wygięte narzędzie rolnicze z długim kosiskiem służyło dawniej do koszenia zbóż i traw na dużą skalę?", kategoria: "Inne", odpowiedź: "Kosa" },
  { pytanie: "Na którym słynnym paryskim placu, od którego rozchodzi się dwanaście alei, zlokalizowany jest monumentalny Łuk Triumfalny?", kategoria: "Geografia", odpowiedź: "Na placu Charles'a de Gaulle'a (dawniej Plac Gwiazdy)" },
  { pytanie: "Który z dwóch oceanów posiada obiektywnie większą powierzchnię całkowitą: Ocean Indyjski czy Ocean Atlantycki?", kategoria: "Geografia", odpowiedź: "Ocean Atlantycki" },
  { pytanie: "W którym polskim mieście odbyła się w 1764 roku uroczysta koronacja ostatniego króla Polski, Stanisława Augusta Poniatowskiego?", kategoria: "Historia Polski", odpowiedź: "W Warszawie (w kolegiacie św. Jana)" },
  { pytanie: "W którym wieku rozpoczęła się w Anglii tak zwana rewolucja przemysłowa, związana m.in. z masowym użyciem maszyny parowej?", kategoria: "Historia", odpowiedź: "W XVIII wieku" },
  { pytanie: "Czy na współczesny obszar geograficzny Polski w czasach historycznych lub geologicznych spadły kiedykolwiek udokumentowane meteoryty?", kategoria: "Geografia Polski/Astronomia", odpowiedź: "Tak (np. meteoryt Morasko)" },
  { pytanie: "Reprezentacja którego kraju zdobyła złoty medal na Mistrzostwach Świata w piłce ręcznej mężczyzn w styczniu 2013 roku?", kategoria: "Sport", odpowiedź: "Hiszpania" },
  { pytanie: "Który genialny artysta dojrzałego renesansu jest autorem słynnego obrazu olejnego 'Święta Anna Samotrzecia'?", kategoria: "Sztuka", odpowiedź: "Leonardo da Vinci" },
  { pytanie: "W którym europejskim państwie w XVI wieku narodził się ludowy, improwizowany typ widowiska teatralnego zwany commedia dell'arte?", kategoria: "Sztuka/Teatr", odpowiedź: "We Włoszech" },
  { pytanie: "Jak w fizyce i optyce nazywamy wielobarwny obraz powstały po rozszczepieniu światła białego przez pryzmat?", kategoria: "Fizyka", odpowiedź: "Widmo (lub spektrum)" },
  { pytanie: "Jak w mitologii skandynawskiej nazywały się ujeżdżające wilki dziewice, służki Odyna, sprowadzające poległych wojowników do Walhalli?", kategoria: "Mitologia", odpowiedź: "Walkirie" },
  { pytanie: "Czy genialny kompozytor Wolfgang Amadeusz Mozart żył i tworzył w czasach panowania austriackiej cesarzowej Marii Teresy?", kategoria: "Muzyka/Historia", odpowiedź: "Tak" }
];